#!/usr/bin/env python3
# Author: Ximan Ding (x.ding25@imperial.ac.uk)
# Script: 15_prepare_shap_tables.py
# Description:
#     Summarise row-level Random Forest and XGBoost SHAP results into
#     publication-ready global, subgroup, zero-recovery and local-case tables.
#
#     This script:
#     1. Reads the RF and XGBoost row-level SHAP outputs generated by
#        14_compute_shap_results.py;
#     2. Calculates global mean absolute SHAP importance;
#     3. Calculates SHAP importance within reference-abundance groups;
#     4. Calculates SHAP importance within shallow-detection groups;
#     5. Extracts shallow-zero but reference-positive OTU records;
#     6. Selects representative local explanation cases;
#     7. Saves summary tables and analysis settings.
#
# Inputs:
#     results/shap/02_random_forest_shap_values.pkl.gz
#     results/shap/03_xgboost_shap_values.pkl.gz
#
# Outputs:
#     results/shap/04_global_shap_importance.csv
#     results/shap/05_subgroup_shap_importance.csv
#     results/shap/06_zero_recovery_shap_values.pkl.gz
#     results/shap/06_zero_recovery_shap_values_preview.csv
#     results/shap/07_local_shap_cases.csv
#     results/shap/shap_summary_config.json
#
# Arguments: None
# Date: July 2026

from pathlib import Path
import json
import time

import numpy as np
import pandas as pd

from _paths import (
    SHAP_DIR,
    banner,
    out,
)


# ============================================================
# 1. Model feature columns
#
# Names and order must match 14_compute_shap_results.py.
# ============================================================

FEATURE_COLUMNS = [
    "log1p_shallow_count",
    "log10_shallow_ra",
    "zero_in_shallow",
    "shallow_rank_norm",
    "shallow_richness",
    "otu_mean_ra_train",
    "otu_prevalence_train",
    "otu_std_ra_train",
    "otu_max_ra_train",
    "is_other",
]


# ============================================================
# 2. Input files
# ============================================================

RF_SHAP_FILE = (
    SHAP_DIR
    / "02_random_forest_shap_values.pkl.gz"
)

XGB_SHAP_FILE = (
    SHAP_DIR
    / "03_xgboost_shap_values.pkl.gz"
)


# ============================================================
# 3. Output files
# ============================================================

GLOBAL_IMPORTANCE_FILE = out(
    "04_global_shap_importance.csv",
    SHAP_DIR,
)

SUBGROUP_IMPORTANCE_FILE = out(
    "05_subgroup_shap_importance.csv",
    SHAP_DIR,
)

ZERO_RECOVERY_FILE = out(
    "06_zero_recovery_shap_values.pkl.gz",
    SHAP_DIR,
)

ZERO_RECOVERY_PREVIEW_FILE = out(
    "06_zero_recovery_shap_values_preview.csv",
    SHAP_DIR,
)

LOCAL_CASES_FILE = out(
    "07_local_shap_cases.csv",
    SHAP_DIR,
)

CONFIG_FILE = out(
    "shap_summary_config.json",
    SHAP_DIR,
)


# ============================================================
# 4. Helper functions
# ============================================================

def require_file(file_path: Path) -> None:
    """Raise a clear error if a required input file is missing."""

    if not file_path.exists():
        raise FileNotFoundError(
            f"Required file not found:\n{file_path}\n\n"
            "Run 14_compute_shap_results.py first."
        )


def validate_shap_table(
    shap_table: pd.DataFrame,
    expected_model_name: str,
) -> None:
    """Check that a row-level SHAP table contains required columns."""

    required_columns = {
        "sample_id",
        "subsample_repeat",
        "otu_id",
        "shallow_depth",
        "shallow_count",
        "shallow_ra",
        "zero_in_shallow",
        "target_reference_ra",
        "target_log10_reference_ra",
        "pred_raw_shallow_ra",
        "pred_random_forest_ra",
        "pred_xgboost_ra",
        "abundance_group",
        "shallow_detection_group",
        "SHAP_base_value",
        "SHAP_sum",
        "SHAP_reconstructed_log_prediction",
        "model",
    }

    required_columns.update(
        f"SHAP__{feature}"
        for feature in FEATURE_COLUMNS
    )

    missing_columns = sorted(
        required_columns
        - set(shap_table.columns)
    )

    if missing_columns:
        raise ValueError(
            f"{expected_model_name} SHAP table is missing columns:\n"
            f"{missing_columns}"
        )

    observed_models = set(
        shap_table["model"]
        .dropna()
        .astype(str)
        .unique()
    )

    if observed_models != {expected_model_name}:
        raise ValueError(
            f"Unexpected model label(s) in {expected_model_name} "
            f"SHAP table: {sorted(observed_models)}"
        )

    shap_columns = [
        f"SHAP__{feature}"
        for feature in FEATURE_COLUMNS
    ]

    finite_check = (
        shap_table[shap_columns]
        .replace([np.inf, -np.inf], np.nan)
    )

    if finite_check.isna().any().any():
        invalid_counts = (
            finite_check
            .isna()
            .sum()
        )

        invalid_counts = invalid_counts.loc[
            invalid_counts > 0
        ]

        raise ValueError(
            f"{expected_model_name} SHAP values contain missing "
            "or infinite values:\n"
            f"{invalid_counts.to_string()}"
        )


def calculate_global_importance(
    shap_table: pd.DataFrame,
    model_name: str,
) -> pd.DataFrame:
    """
    Calculate global SHAP importance.

    mean_abs_SHAP:
        Mean absolute SHAP value across all sampled rows.

    mean_signed_SHAP:
        Mean signed SHAP value across all sampled rows.

    importance_percent:
        Percentage of total mean absolute SHAP importance.
    """

    records = []

    for feature in FEATURE_COLUMNS:
        shap_column = f"SHAP__{feature}"

        feature_values = pd.to_numeric(
            shap_table[shap_column],
            errors="coerce",
        )

        records.append(
            {
                "model": model_name,
                "feature": feature,
                "mean_abs_SHAP": float(
                    feature_values.abs().mean()
                ),
                "mean_signed_SHAP": float(
                    feature_values.mean()
                ),
            }
        )

    result = pd.DataFrame(records)

    total_importance = (
        result["mean_abs_SHAP"].sum()
    )

    if total_importance > 0:
        result["importance_percent"] = (
            result["mean_abs_SHAP"]
            / total_importance
            * 100.0
        )
    else:
        result["importance_percent"] = np.nan

    result = (
        result
        .sort_values(
            "mean_abs_SHAP",
            ascending=False,
        )
        .reset_index(drop=True)
    )

    result["importance_rank"] = (
        np.arange(
            1,
            len(result) + 1,
        )
    )

    return result[
        [
            "model",
            "importance_rank",
            "feature",
            "mean_abs_SHAP",
            "importance_percent",
            "mean_signed_SHAP",
        ]
    ]


def calculate_subgroup_importance(
    shap_table: pd.DataFrame,
    model_name: str,
    subgroup_column: str,
) -> pd.DataFrame:
    """
    Calculate mean absolute SHAP importance within each subgroup.

    Examples:
        abundance_group
        shallow_detection_group
    """

    records = []

    for subgroup_value, current_group in shap_table.groupby(
        subgroup_column,
        observed=True,
        sort=False,
    ):
        if current_group.empty:
            continue

        group_records = []

        for feature in FEATURE_COLUMNS:
            shap_column = f"SHAP__{feature}"

            mean_abs_shap = float(
                pd.to_numeric(
                    current_group[shap_column],
                    errors="coerce",
                )
                .abs()
                .mean()
            )

            mean_signed_shap = float(
                pd.to_numeric(
                    current_group[shap_column],
                    errors="coerce",
                )
                .mean()
            )

            group_records.append(
                {
                    "model": model_name,
                    "subgroup_variable": subgroup_column,
                    "subgroup": str(subgroup_value),
                    "number_of_rows": int(
                        len(current_group)
                    ),
                    "feature": feature,
                    "mean_abs_SHAP": mean_abs_shap,
                    "mean_signed_SHAP": mean_signed_shap,
                }
            )

        group_result = pd.DataFrame(
            group_records
        )

        total_importance = (
            group_result["mean_abs_SHAP"].sum()
        )

        if total_importance > 0:
            group_result["importance_percent"] = (
                group_result["mean_abs_SHAP"]
                / total_importance
                * 100.0
            )
        else:
            group_result["importance_percent"] = np.nan

        group_result = (
            group_result
            .sort_values(
                "mean_abs_SHAP",
                ascending=False,
            )
            .reset_index(drop=True)
        )

        group_result["importance_rank"] = (
            np.arange(
                1,
                len(group_result) + 1,
            )
        )

        records.append(
            group_result
        )

    if not records:
        return pd.DataFrame(
            columns=[
                "model",
                "subgroup_variable",
                "subgroup",
                "number_of_rows",
                "importance_rank",
                "feature",
                "mean_abs_SHAP",
                "importance_percent",
                "mean_signed_SHAP",
            ]
        )

    result = pd.concat(
        records,
        ignore_index=True,
    )

    return result[
        [
            "model",
            "subgroup_variable",
            "subgroup",
            "number_of_rows",
            "importance_rank",
            "feature",
            "mean_abs_SHAP",
            "importance_percent",
            "mean_signed_SHAP",
        ]
    ]


def add_prediction_error_columns(
    shap_table: pd.DataFrame,
    prediction_column: str,
) -> pd.DataFrame:
    """Add model and Raw prediction-error columns."""

    current = shap_table.copy()

    current["model_prediction_ra"] = pd.to_numeric(
        current[prediction_column],
        errors="coerce",
    )

    current["model_absolute_error"] = np.abs(
        current["model_prediction_ra"]
        - current["target_reference_ra"]
    )

    current["raw_absolute_error"] = np.abs(
        current["pred_raw_shallow_ra"]
        - current["target_reference_ra"]
    )

    current["model_improvement_over_raw"] = (
        current["raw_absolute_error"]
        - current["model_absolute_error"]
    )

    current["model_correction_over_raw"] = (
        current["model_prediction_ra"]
        - current["pred_raw_shallow_ra"]
    )

    return current


def select_local_cases(
    shap_table: pd.DataFrame,
    model_name: str,
) -> pd.DataFrame:
    """
    Select representative rows for later local SHAP plots.

    Cases:
        1. Highest reference RA;
        2. Largest positive shallow-zero recovery;
        3. Smallest absolute model error;
        4. Largest absolute model error.
    """

    prediction_column_map = {
        "Random Forest": "pred_random_forest_ra",
        "XGBoost": "pred_xgboost_ra",
    }

    prediction_column = (
        prediction_column_map[model_name]
    )

    current = add_prediction_error_columns(
        shap_table=shap_table,
        prediction_column=prediction_column,
    )

    selected_rows = []

    # --------------------------------------------------------
    # Case 1: Highest reference abundance
    # --------------------------------------------------------

    highest_reference_row = (
        current
        .nlargest(
            1,
            "target_reference_ra",
        )
        .copy()
    )

    highest_reference_row[
        "local_case_type"
    ] = "Highest reference RA"

    selected_rows.append(
        highest_reference_row
    )

    # --------------------------------------------------------
    # Case 2: Largest positive shallow-zero recovery
    # --------------------------------------------------------

    zero_candidates = current.loc[
        (
            current["zero_in_shallow"] == 1
        )
        & (
            current["target_reference_ra"] > 0
        )
    ].copy()

    if not zero_candidates.empty:
        zero_recovery_row = (
            zero_candidates
            .nlargest(
                1,
                "model_correction_over_raw",
            )
            .copy()
        )

        zero_recovery_row[
            "local_case_type"
        ] = "Largest positive zero recovery"

        selected_rows.append(
            zero_recovery_row
        )

    # --------------------------------------------------------
    # Case 3: Smallest model error
    # --------------------------------------------------------

    smallest_error_row = (
        current
        .nsmallest(
            1,
            "model_absolute_error",
        )
        .copy()
    )

    smallest_error_row[
        "local_case_type"
    ] = "Smallest absolute error"

    selected_rows.append(
        smallest_error_row
    )

    # --------------------------------------------------------
    # Case 4: Largest model error
    # --------------------------------------------------------

    largest_error_row = (
        current
        .nlargest(
            1,
            "model_absolute_error",
        )
        .copy()
    )

    largest_error_row[
        "local_case_type"
    ] = "Largest absolute error"

    selected_rows.append(
        largest_error_row
    )

    result = pd.concat(
        selected_rows,
        ignore_index=True,
    )

    result["selected_prediction_column"] = (
        prediction_column
    )

    return result


# ============================================================
# 5. Main analysis
# ============================================================

def main() -> None:
    """Prepare summary tables from row-level SHAP outputs."""

    overall_start = time.time()

    # --------------------------------------------------------
    # Step 1: Read and validate SHAP values
    # --------------------------------------------------------

    banner(
        "Step 1: Read row-level SHAP results"
    )

    require_file(
        RF_SHAP_FILE
    )

    require_file(
        XGB_SHAP_FILE
    )

    rf_shap_table = pd.read_pickle(
        RF_SHAP_FILE
    )

    xgb_shap_table = pd.read_pickle(
        XGB_SHAP_FILE
    )

    validate_shap_table(
        shap_table=rf_shap_table,
        expected_model_name="Random Forest",
    )

    validate_shap_table(
        shap_table=xgb_shap_table,
        expected_model_name="XGBoost",
    )

    print(
        "Random Forest SHAP table shape: "
        f"{rf_shap_table.shape}"
    )

    print(
        "XGBoost SHAP table shape: "
        f"{xgb_shap_table.shape}"
    )

    # --------------------------------------------------------
    # Step 2: Calculate global importance
    # --------------------------------------------------------

    banner(
        "Step 2: Calculate global SHAP importance"
    )

    rf_global_importance = (
        calculate_global_importance(
            shap_table=rf_shap_table,
            model_name="Random Forest",
        )
    )

    xgb_global_importance = (
        calculate_global_importance(
            shap_table=xgb_shap_table,
            model_name="XGBoost",
        )
    )

    global_importance = pd.concat(
        [
            rf_global_importance,
            xgb_global_importance,
        ],
        ignore_index=True,
    )

    global_importance.to_csv(
        GLOBAL_IMPORTANCE_FILE,
        index=False,
        encoding="utf-8-sig",
    )

    print(
        global_importance[
            [
                "model",
                "importance_rank",
                "feature",
                "mean_abs_SHAP",
                "importance_percent",
            ]
        ]
        .to_string(index=False)
    )

    print(
        f"\nSaved: {GLOBAL_IMPORTANCE_FILE}"
    )

    # --------------------------------------------------------
    # Step 3: Calculate subgroup importance
    # --------------------------------------------------------

    banner(
        "Step 3: Calculate subgroup SHAP importance"
    )

    subgroup_results = []

    for model_name, shap_table in [
        (
            "Random Forest",
            rf_shap_table,
        ),
        (
            "XGBoost",
            xgb_shap_table,
        ),
    ]:
        subgroup_results.append(
            calculate_subgroup_importance(
                shap_table=shap_table,
                model_name=model_name,
                subgroup_column="abundance_group",
            )
        )

        subgroup_results.append(
            calculate_subgroup_importance(
                shap_table=shap_table,
                model_name=model_name,
                subgroup_column="shallow_detection_group",
            )
        )

    subgroup_importance = pd.concat(
        subgroup_results,
        ignore_index=True,
    )

    subgroup_importance.to_csv(
        SUBGROUP_IMPORTANCE_FILE,
        index=False,
        encoding="utf-8-sig",
    )

    subgroup_counts = (
        subgroup_importance[
            [
                "model",
                "subgroup_variable",
                "subgroup",
                "number_of_rows",
            ]
        ]
        .drop_duplicates()
    )

    print(
        subgroup_counts.to_string(
            index=False
        )
    )

    print(
        f"\nSaved: {SUBGROUP_IMPORTANCE_FILE}"
    )

    # --------------------------------------------------------
    # Step 4: Export shallow-zero recovery rows
    # --------------------------------------------------------

    banner(
        "Step 4: Export shallow-zero recovery SHAP rows"
    )

    zero_rf = rf_shap_table.loc[
        (
            rf_shap_table["zero_in_shallow"] == 1
        )
        & (
            rf_shap_table["target_reference_ra"] > 0
        )
    ].copy()

    zero_xgb = xgb_shap_table.loc[
        (
            xgb_shap_table["zero_in_shallow"] == 1
        )
        & (
            xgb_shap_table["target_reference_ra"] > 0
        )
    ].copy()

    zero_shap_table = pd.concat(
        [
            zero_rf,
            zero_xgb,
        ],
        ignore_index=True,
    )

    zero_shap_table.to_pickle(
        ZERO_RECOVERY_FILE,
        compression="gzip",
    )

    zero_shap_table.to_csv(
        ZERO_RECOVERY_PREVIEW_FILE,
        index=False,
        encoding="utf-8-sig",
    )

    zero_counts = (
        zero_shap_table["model"]
        .value_counts()
    )

    print(
        "Shallow-zero but reference-positive rows:"
    )

    print(
        zero_counts.to_string()
    )

    print(
        f"\nSaved: {ZERO_RECOVERY_FILE}"
    )

    print(
        f"Saved: {ZERO_RECOVERY_PREVIEW_FILE}"
    )

    # --------------------------------------------------------
    # Step 5: Select representative local cases
    # --------------------------------------------------------

    banner(
        "Step 5: Select representative local SHAP cases"
    )

    rf_local_cases = select_local_cases(
        shap_table=rf_shap_table,
        model_name="Random Forest",
    )

    xgb_local_cases = select_local_cases(
        shap_table=xgb_shap_table,
        model_name="XGBoost",
    )

    local_cases = pd.concat(
        [
            rf_local_cases,
            xgb_local_cases,
        ],
        ignore_index=True,
    )

    local_cases.to_csv(
        LOCAL_CASES_FILE,
        index=False,
        encoding="utf-8-sig",
    )

    print(
        local_cases[
            [
                "model",
                "local_case_type",
                "sample_id",
                "otu_id",
                "target_reference_ra",
                "pred_raw_shallow_ra",
                "model_prediction_ra",
                "model_absolute_error",
            ]
        ]
        .to_string(index=False)
    )

    print(
        f"\nSaved: {LOCAL_CASES_FILE}"
    )

    # --------------------------------------------------------
    # Step 6: Save summary configuration
    # --------------------------------------------------------

    banner(
        "Step 6: Save SHAP summary settings"
    )

    config = {
        "random_forest_shap_file": str(
            RF_SHAP_FILE
        ),
        "xgboost_shap_file": str(
            XGB_SHAP_FILE
        ),
        "output_directory": str(
            SHAP_DIR
        ),
        "feature_columns": (
            FEATURE_COLUMNS
        ),
        "global_importance_definition": (
            "Mean absolute SHAP value across the fixed "
            "independent-test-set SHAP sample."
        ),
        "subgroup_variables": [
            "abundance_group",
            "shallow_detection_group",
        ],
        "zero_recovery_definition": (
            "zero_in_shallow == 1 and "
            "target_reference_ra > 0"
        ),
        "local_case_types": [
            "Highest reference RA",
            "Largest positive zero recovery",
            "Smallest absolute error",
            "Largest absolute error",
        ],
        "interpretation_warning": (
            "SHAP values explain the pre-normalisation model "
            "output on the log10(reference_RA + 1e-8) scale. "
            "They describe predictive associations and do not "
            "establish ecological causality."
        ),
    }

    with open(
        CONFIG_FILE,
        "w",
        encoding="utf-8",
    ) as file:
        json.dump(
            config,
            file,
            ensure_ascii=False,
            indent=2,
        )

    print(
        f"Saved: {CONFIG_FILE}"
    )

    # --------------------------------------------------------
    # Completion summary
    # --------------------------------------------------------

    banner(
        "SHAP summary tables completed successfully"
    )

    print(
        "Created files:"
    )

    output_files = [
        GLOBAL_IMPORTANCE_FILE,
        SUBGROUP_IMPORTANCE_FILE,
        ZERO_RECOVERY_FILE,
        ZERO_RECOVERY_PREVIEW_FILE,
        LOCAL_CASES_FILE,
        CONFIG_FILE,
    ]

    for file_path in output_files:
        try:
            relative_path = (
                file_path
                .relative_to(
                    SHAP_DIR.parent
                )
            )

            print(
                f"  - results/{relative_path}"
            )

        except ValueError:
            print(
                f"  - {file_path}"
            )

    print(
        "\nTotal runtime: "
        f"{(time.time() - overall_start) / 60:.2f} minutes"
    )


if __name__ == "__main__":
    main()