#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Author: Ximan Ding (x.ding25@imperial.ac.uk)
# Script: 16_plot_core_figures.py
# Description:
#     Generate the five compact core model-performance figures for the
#     shallow-to-high-depth 16S relative-abundance recovery analysis.
#
#     This script:
#     1. Reads biological-sample-level test metrics prepared by
#        12_prepare_statistical_tables.py;
#     2. Reads paired sample improvements prepared by
#        13_run_statistical_comparisons.py;
#     3. Reads abundance-group and shallow-zero improvements prepared by
#        12_prepare_statistical_tables.py;
#     4. Reads test-set predictions generated by
#        11_generate_predictions_and_metrics.py;
#     5. Produces five multi-panel figures for model performance,
#        paired improvements, prediction agreement, RAD reconstruction,
#        and low-abundance recovery.
#
# Inputs:
#     results/intermediate/12_test_sample_level_metrics.csv
#     results/intermediate/13_paired_sample_improvements.csv
#     results/statistics/12_abundance_group_improvement_vs_raw.csv
#     results/statistics/12_zero_recovery_improvement_vs_raw.csv
#     results/intermediate/11_predictions_test.pkl.gz
#
# Outputs:
#     results/figures/Figure1_primary_metrics_combined.png
#     results/figures/Figure1_primary_metrics_combined.pdf
#     results/figures/Figure1_primary_metrics_combined.svg
#     results/figures/Figure2_sample_level_improvement_combined.png
#     results/figures/Figure2_sample_level_improvement_combined.pdf
#     results/figures/Figure2_sample_level_improvement_combined.svg
#     results/figures/Figure3_true_vs_pred_hexbin_combined.png
#     results/figures/Figure3_true_vs_pred_hexbin_combined.pdf
#     results/figures/Figure3_true_vs_pred_hexbin_combined.svg
#     results/figures/Figure4_RAD_examples_combined.png
#     results/figures/Figure4_RAD_examples_combined.pdf
#     results/figures/Figure4_RAD_examples_combined.svg
#     results/figures/Figure5_zero_recovery_and_abundance_combined.png
#     results/figures/Figure5_zero_recovery_and_abundance_combined.pdf
#     results/figures/Figure5_zero_recovery_and_abundance_combined.svg
#
# Arguments: None
# Date: July 2026

# ============================================================
# 0. Import packages
# ============================================================

from pathlib import Path
from typing import Iterable, Sequence
import warnings

import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns


warnings.filterwarnings("ignore", category=FutureWarning)


# ============================================================
# 1. Project paths
# ============================================================

# The script is expected to be stored in:
# CMEE_MRes_Project/code/16_plot_core_figures.py
PROJECT_ROOT = Path(__file__).resolve().parents[1]

RESULTS_DIR = PROJECT_ROOT / "results"
INTERMEDIATE_DIR = RESULTS_DIR / "intermediate"
STATISTICS_DIR = RESULTS_DIR / "statistics"
OUTPUT_DIR = RESULTS_DIR / "figures"

PRIMARY_METRICS_FILE = (
    INTERMEDIATE_DIR / "12_test_sample_level_metrics.csv"
)

PAIRED_IMPROVEMENT_FILE = (
    INTERMEDIATE_DIR / "13_paired_sample_improvements.csv"
)

ABUNDANCE_IMPROVEMENT_FILE = (
    STATISTICS_DIR / "12_abundance_group_improvement_vs_raw.csv"
)

ZERO_IMPROVEMENT_FILE = (
    STATISTICS_DIR / "12_zero_recovery_improvement_vs_raw.csv"
)

TEST_PREDICTION_FILE = (
    INTERMEDIATE_DIR / "11_predictions_test.pkl.gz"
)


# ============================================================
# 2. Global plotting style
# ============================================================

mpl.rcParams["font.family"] = "serif"
mpl.rcParams["font.serif"] = ["Times New Roman", "DejaVu Serif"]
mpl.rcParams["font.weight"] = "bold"
mpl.rcParams["axes.labelweight"] = "bold"
mpl.rcParams["axes.titleweight"] = "bold"
mpl.rcParams["axes.linewidth"] = 1.3
mpl.rcParams["axes.unicode_minus"] = False
mpl.rcParams["xtick.major.width"] = 1.1
mpl.rcParams["ytick.major.width"] = 1.1
mpl.rcParams["xtick.direction"] = "out"
mpl.rcParams["ytick.direction"] = "out"
mpl.rcParams["savefig.bbox"] = "tight"

sns.set_theme(style="white")


# ============================================================
# 3. Analysis constants
# ============================================================

PSEUDO_COUNT = 1e-8
HEXBIN_SAMPLE_SIZE = 50_000
RANDOM_STATE = 42
RAD_REPEAT_ID = 1

METHOD_ORDER = [
    "Raw shallow RA",
    "Training-mean RA",
    "Random Forest",
    "XGBoost",
]

METHOD_SHORT = {
    "Raw shallow RA": "Raw",
    "Training-mean RA": "Mean",
    "Random Forest": "RF",
    "XGBoost": "XGB",
}

METHOD_COLORS = {
    "Raw shallow RA": "#7F7F7F",
    "Training-mean RA": "#D9A441",
    "Random Forest": "#3B82B4",
    "XGBoost": "#D65F5F",
}

PRIMARY_METRICS = [
    "Bray_Curtis",
    "Jensen_Shannon_distance",
    "RAD_RMSE_log10_RA_specific",
    "RAD_tail_MAE_log10",
    "Shannon_absolute_error",
    "richness_1read_absolute_error",
]

METRIC_LABELS = {
    "Bray_Curtis": "Bray-Curtis distance",
    "Jensen_Shannon_distance": "Jensen-Shannon distance",
    "RAD_RMSE_log10_RA_specific": "RAD log10-RMSE",
    "RAD_tail_MAE_log10": "RAD tail log10-MAE",
    "Shannon_absolute_error": "Shannon absolute error",
    "richness_1read_absolute_error": "Richness absolute error",
}

TARGET_COMPARISONS = [
    "Random Forest vs Raw shallow RA",
    "XGBoost vs Raw shallow RA",
]

COMPARISON_SHORT = {
    "Random Forest vs Raw shallow RA": "RF vs Raw",
    "XGBoost vs Raw shallow RA": "XGB vs Raw",
}

COMPARISON_ORDER = [
    "RF vs Raw",
    "XGB vs Raw",
]

COMPARISON_COLORS = {
    "RF vs Raw": METHOD_COLORS["Random Forest"],
    "XGB vs Raw": METHOD_COLORS["XGBoost"],
}

ABUNDANCE_ORDER = [
    "Dominant (>=1e-2)",
    "Common (1e-3 to 1e-2)",
    "Rare (1e-4 to 1e-3)",
    "Very rare (<1e-4)",
    "Reference zero",
]

ABUNDANCE_SHORT = {
    "Dominant (>=1e-2)": "Dominant",
    "Common (1e-3 to 1e-2)": "Common",
    "Rare (1e-4 to 1e-3)": "Rare",
    "Very rare (<1e-4)": "Very rare",
    "Reference zero": "Ref. zero",
}

ZERO_METRIC_ORDER = [
    "MAE_RA",
    "RMSE_RA",
    "MAE_log10_RA",
    "RMSE_log10_RA",
]

ZERO_METRIC_LABELS = {
    "MAE_RA": "MAE\n(RA)",
    "RMSE_RA": "RMSE\n(RA)",
    "MAE_log10_RA": "MAE\n(log10)",
    "RMSE_log10_RA": "RMSE\n(log10)",
}

PREDICTION_COLUMNS = {
    "Raw shallow RA": "pred_raw_shallow_ra",
    "Random Forest": "pred_random_forest_ra",
    "XGBoost": "pred_xgboost_ra",
}


# ============================================================
# 4. Helper functions
# ============================================================

def print_step(step_number: int, message: str) -> None:
    """Print one formatted progress heading."""

    print("\n" + "=" * 92)
    print(f"Step {step_number}: {message}")
    print("=" * 92)


def require_file(file_path: Path) -> None:
    """Raise a clear error when one required input file is missing."""

    if not file_path.is_file():
        raise FileNotFoundError(
            "Required input file was not found:\n"
            f"{file_path}\n"
            "Run scripts 11, 12 and 13 before running this script."
        )


def require_columns(
    data: pd.DataFrame,
    required_columns: Iterable[str],
    table_name: str,
) -> None:
    """Raise a clear error when a table lacks required columns."""

    missing_columns = [
        column
        for column in required_columns
        if column not in data.columns
    ]

    if missing_columns:
        raise KeyError(
            f"{table_name} is missing required columns:\n"
            f"{missing_columns}\n"
            f"Available columns:\n{data.columns.tolist()}"
        )


def first_existing_column(
    data: pd.DataFrame,
    candidates: Sequence[str],
    table_name: str,
) -> str:
    """Return the first available column from a list of accepted names."""

    for column in candidates:
        if column in data.columns:
            return column

    raise KeyError(
        f"{table_name} does not contain any accepted column name from:\n"
        f"{list(candidates)}\n"
        f"Available columns:\n{data.columns.tolist()}"
    )


def normalise_method_names(data: pd.DataFrame, column: str) -> pd.DataFrame:
    """Standardise short model labels to the full project method names."""

    replacements = {
        "Raw": "Raw shallow RA",
        "Mean": "Training-mean RA",
        "Training mean": "Training-mean RA",
        "RF": "Random Forest",
        "RandomForest": "Random Forest",
        "XGB": "XGBoost",
    }

    output = data.copy()
    output[column] = output[column].replace(replacements)
    return output


def normalise_abundance_groups(data: pd.DataFrame, column: str) -> pd.DataFrame:
    """Standardise abundance-group labels used by Stage 12."""

    replacements = {
        "Dominant": "Dominant (>=1e-2)",
        "Common": "Common (1e-3 to 1e-2)",
        "Rare": "Rare (1e-4 to 1e-3)",
        "Very rare": "Very rare (<1e-4)",
        "Reference Zero": "Reference zero",
        "Reference-zero": "Reference zero",
        "Reference_zero": "Reference zero",
    }

    output = data.copy()
    output[column] = output[column].replace(replacements)
    return output


def save_figure(fig: plt.Figure, base_name: str) -> None:
    """Save one figure in PNG, PDF and SVG formats."""

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    output_paths = [
        OUTPUT_DIR / f"{base_name}.png",
        OUTPUT_DIR / f"{base_name}.pdf",
        OUTPUT_DIR / f"{base_name}.svg",
    ]

    fig.savefig(
        output_paths[0],
        dpi=600,
        facecolor="white",
    )
    fig.savefig(
        output_paths[1],
        facecolor="white",
    )
    fig.savefig(
        output_paths[2],
        facecolor="white",
    )

    for output_path in output_paths:
        print(f"Saved: {output_path}")


def beautify_axis(
    ax: plt.Axes,
    xlabel: str = "",
    ylabel: str = "",
    title: str = "",
    rotate_x: int = 0,
) -> None:
    """Apply consistent axis formatting."""

    ax.set_xlabel(xlabel, fontsize=10.5, fontweight="bold")
    ax.set_ylabel(ylabel, fontsize=10.5, fontweight="bold")
    ax.set_title(title, fontsize=11.5, fontweight="bold", pad=8)
    ax.tick_params(axis="both", labelsize=9, width=1.0, length=4)

    for tick in ax.get_xticklabels():
        tick.set_rotation(rotate_x)
        tick.set_fontweight("bold")

    for tick in ax.get_yticklabels():
        tick.set_fontweight("bold")

    for spine in ax.spines.values():
        spine.set_linewidth(1.2)

    ax.grid(
        axis="y",
        linestyle="--",
        linewidth=0.6,
        alpha=0.28,
    )


def safe_compositional_normalisation(values: np.ndarray) -> np.ndarray:
    """Normalise a non-negative vector to one and reject invalid vectors."""

    values = np.asarray(values, dtype=float)
    values = np.clip(values, 0.0, None)

    total = float(values.sum())

    if not np.isfinite(total) or total <= 0:
        raise ValueError(
            "A compositional vector has a non-positive or non-finite sum."
        )

    return values / total


def choose_representative_samples(
    prediction_df: pd.DataFrame,
) -> list[str]:
    """
    Select best, median and worst Random Forest samples according to
    mean Bray-Curtis distance across shallow-sequencing repeats.
    """

    sample_records = []

    for sample_id, sample_data in prediction_df.groupby(
        "sample_id",
        observed=True,
        sort=False,
    ):
        repeat_distances = []

        for _, repeat_data in sample_data.groupby(
            "subsample_repeat",
            observed=True,
            sort=False,
        ):
            repeat_data = repeat_data.loc[
                repeat_data["otu_id"].astype(str) != "OTHER"
            ].copy()

            true_values = safe_compositional_normalisation(
                repeat_data["target_reference_ra"].to_numpy(dtype=float)
            )

            rf_values = safe_compositional_normalisation(
                repeat_data["pred_random_forest_ra"].to_numpy(dtype=float)
            )

            bray_curtis = 0.5 * np.sum(
                np.abs(true_values - rf_values)
            )

            repeat_distances.append(float(bray_curtis))

        if repeat_distances:
            sample_records.append(
                {
                    "sample_id": str(sample_id),
                    "rf_mean_bray_curtis": float(
                        np.mean(repeat_distances)
                    ),
                }
            )

    sample_performance = (
        pd.DataFrame(sample_records)
        .sort_values(
            "rf_mean_bray_curtis",
            ascending=True,
        )
        .reset_index(drop=True)
    )

    if sample_performance.empty:
        raise ValueError(
            "No eligible samples were available for RAD selection."
        )

    if len(sample_performance) < 3:
        return sample_performance["sample_id"].tolist()

    return [
        str(sample_performance.iloc[0]["sample_id"]),
        str(
            sample_performance.iloc[
                len(sample_performance) // 2
            ]["sample_id"]
        ),
        str(sample_performance.iloc[-1]["sample_id"]),
    ]


def get_one_repeat_sample(
    prediction_df: pd.DataFrame,
    sample_id: str,
    repeat_id: int = RAD_REPEAT_ID,
) -> pd.DataFrame:
    """Return one shallow repeat for one biological sample."""

    sample_ids_as_text = prediction_df["sample_id"].astype(str)

    current = prediction_df.loc[
        sample_ids_as_text == str(sample_id)
    ].copy()

    if current.empty:
        raise ValueError(
            f"sample_id was not found in the prediction table: {sample_id}"
        )

    available_repeats = sorted(
        current["subsample_repeat"].dropna().unique().tolist()
    )

    if not available_repeats:
        raise ValueError(
            f"No shallow repeats were found for sample_id: {sample_id}"
        )

    selected_repeat = (
        repeat_id
        if repeat_id in available_repeats
        else available_repeats[0]
    )

    current = current.loc[
        current["subsample_repeat"] == selected_repeat
    ].copy()

    current = current.loc[
        current["otu_id"].astype(str) != "OTHER"
    ].copy()

    if current.empty:
        raise ValueError(
            f"No specific OTU rows remained for sample_id: {sample_id}"
        )

    return current


def extract_improvement_values(
    data: pd.DataFrame,
    group_column: str,
    group_value: str,
    metric_column: str,
    metric_value: str,
    method_column: str,
    method_value: str,
    value_column: str,
) -> float:
    """Extract one improvement value or return NaN when it is unavailable."""

    selected = data.loc[
        (data[group_column] == group_value)
        & (data[metric_column] == metric_value)
        & (data[method_column] == method_value),
        value_column,
    ]

    if selected.empty:
        return np.nan

    return float(selected.iloc[0])


# ============================================================
# 5. Read and validate input data
# ============================================================

def read_inputs() -> tuple[
    pd.DataFrame,
    pd.DataFrame,
    pd.DataFrame,
    pd.DataFrame,
    pd.DataFrame,
]:
    """Read all plotting inputs and validate their main structure."""

    print_step(1, "Read and validate plotting inputs")

    required_files = [
        PRIMARY_METRICS_FILE,
        PAIRED_IMPROVEMENT_FILE,
        ABUNDANCE_IMPROVEMENT_FILE,
        ZERO_IMPROVEMENT_FILE,
        TEST_PREDICTION_FILE,
    ]

    for file_path in required_files:
        require_file(file_path)

    sample_level_metrics = pd.read_csv(PRIMARY_METRICS_FILE)
    paired_improvements = pd.read_csv(PAIRED_IMPROVEMENT_FILE)
    abundance_improvements = pd.read_csv(
        ABUNDANCE_IMPROVEMENT_FILE
    )
    zero_improvements = pd.read_csv(ZERO_IMPROVEMENT_FILE)
    test_predictions = pd.read_pickle(TEST_PREDICTION_FILE)

    require_columns(
        sample_level_metrics,
        ["sample_id", "method", *PRIMARY_METRICS],
        "12_test_sample_level_metrics.csv",
    )

    require_columns(
        paired_improvements,
        [
            "sample_id",
            "metric",
            "comparison",
            "oriented_improvement_B_over_A",
        ],
        "13_paired_sample_improvements.csv",
    )

    require_columns(
        test_predictions,
        [
            "sample_id",
            "subsample_repeat",
            "otu_id",
            "target_reference_ra",
            *PREDICTION_COLUMNS.values(),
        ],
        "11_predictions_test.pkl.gz",
    )

    sample_level_metrics = normalise_method_names(
        sample_level_metrics,
        "method",
    )

    print(
        f"Sample-level metrics:       {sample_level_metrics.shape}"
    )
    print(
        f"Paired improvements:        {paired_improvements.shape}"
    )
    print(
        f"Abundance improvements:     {abundance_improvements.shape}"
    )
    print(
        f"Zero-recovery improvements: {zero_improvements.shape}"
    )
    print(
        f"Test predictions:           {test_predictions.shape}"
    )

    print(f"\nFigure output directory:\n{OUTPUT_DIR}")

    return (
        sample_level_metrics,
        paired_improvements,
        abundance_improvements,
        zero_improvements,
        test_predictions,
    )


# ============================================================
# 6. Figure 1: Primary performance metrics
# ============================================================

def plot_primary_metrics(
    sample_level_metrics: pd.DataFrame,
) -> None:
    """Plot distributions of the six primary test metrics."""

    print_step(2, "Create Figure 1: primary test metrics")

    fig, axes = plt.subplots(
        2,
        3,
        figsize=(15.8, 9.5),
    )

    for ax, metric in zip(axes.flat, PRIMARY_METRICS):
        plot_data = sample_level_metrics.loc[
            sample_level_metrics["method"].isin(METHOD_ORDER),
            ["sample_id", "method", metric],
        ].dropna(subset=[metric])

        sns.boxplot(
            data=plot_data,
            x="method",
            y=metric,
            order=METHOD_ORDER,
            palette=METHOD_COLORS,
            width=0.62,
            linewidth=1.1,
            fliersize=0,
            ax=ax,
        )

        sns.stripplot(
            data=plot_data,
            x="method",
            y=metric,
            order=METHOD_ORDER,
            color="black",
            size=2.2,
            jitter=0.20,
            alpha=0.36,
            ax=ax,
        )

        ax.set_xticks(range(len(METHOD_ORDER)))
        ax.set_xticklabels(
            [METHOD_SHORT[method] for method in METHOD_ORDER]
        )

        beautify_axis(
            ax,
            xlabel="Method",
            ylabel=METRIC_LABELS[metric],
            title=METRIC_LABELS[metric],
        )

    fig.suptitle(
        "Figure 1. Test-sample performance across primary metrics",
        fontsize=15,
        fontweight="bold",
        y=0.995,
    )

    fig.tight_layout(rect=(0, 0, 1, 0.97))

    save_figure(
        fig,
        "Figure1_primary_metrics_combined",
    )
    plt.close(fig)


# ============================================================
# 7. Figure 2: Paired improvement relative to Raw
# ============================================================

def plot_sample_improvements(
    paired_improvements: pd.DataFrame,
) -> None:
    """Plot paired biological-sample improvements relative to Raw."""

    print_step(
        3,
        "Create Figure 2: paired improvements over Raw shallow RA",
    )

    fig, axes = plt.subplots(
        2,
        3,
        figsize=(15.8, 9.5),
    )

    for ax, metric in zip(axes.flat, PRIMARY_METRICS):
        current = paired_improvements.loc[
            (paired_improvements["metric"] == metric)
            & (
                paired_improvements["comparison"].isin(
                    TARGET_COMPARISONS
                )
            )
        ].copy()

        if current.empty:
            raise ValueError(
                "No paired-improvement rows were found for metric: "
                f"{metric}"
            )

        current["comparison_short"] = (
            current["comparison"].map(COMPARISON_SHORT)
        )

        sns.boxplot(
            data=current,
            x="comparison_short",
            y="oriented_improvement_B_over_A",
            order=COMPARISON_ORDER,
            palette=COMPARISON_COLORS,
            width=0.55,
            linewidth=1.1,
            fliersize=0,
            ax=ax,
        )

        sns.stripplot(
            data=current,
            x="comparison_short",
            y="oriented_improvement_B_over_A",
            order=COMPARISON_ORDER,
            color="black",
            size=2.2,
            jitter=0.18,
            alpha=0.38,
            ax=ax,
        )

        ax.axhline(
            0,
            color="black",
            linestyle="--",
            linewidth=1.0,
        )

        beautify_axis(
            ax,
            xlabel="Comparison",
            ylabel="Improvement over Raw",
            title=METRIC_LABELS[metric],
        )

    fig.suptitle(
        "Figure 2. Sample-level improvement over Raw shallow RA\n"
        "(positive values indicate model improvement)",
        fontsize=15,
        fontweight="bold",
        y=0.995,
    )

    fig.tight_layout(rect=(0, 0, 1, 0.955))

    save_figure(
        fig,
        "Figure2_sample_level_improvement_combined",
    )
    plt.close(fig)


# ============================================================
# 8. Figure 3: Reference vs predicted abundance
# ============================================================

def plot_reference_vs_prediction(
    test_predictions: pd.DataFrame,
) -> None:
    """Plot row-level reference and predicted abundance on log10 scales."""

    print_step(
        4,
        "Create Figure 3: reference vs predicted abundance",
    )

    hexbin_data = test_predictions.loc[
        test_predictions["otu_id"].astype(str) != "OTHER"
    ].copy()

    if hexbin_data.empty:
        raise ValueError(
            "No specific OTU rows were available for Figure 3."
        )

    sample_size = min(
        HEXBIN_SAMPLE_SIZE,
        len(hexbin_data),
    )

    hexbin_data = hexbin_data.sample(
        n=sample_size,
        random_state=RANDOM_STATE,
        replace=False,
    ).copy()

    true_log10 = np.log10(
        np.clip(
            hexbin_data["target_reference_ra"].to_numpy(dtype=float),
            0.0,
            None,
        )
        + PSEUDO_COUNT
    )

    fig, axes = plt.subplots(
        1,
        3,
        figsize=(16.0, 5.2),
    )

    last_hexbin = None

    for ax, (method_name, prediction_column) in zip(
        axes,
        PREDICTION_COLUMNS.items(),
    ):
        predicted_log10 = np.log10(
            np.clip(
                hexbin_data[prediction_column].to_numpy(dtype=float),
                0.0,
                None,
            )
            + PSEUDO_COUNT
        )

        valid_mask = (
            np.isfinite(true_log10)
            & np.isfinite(predicted_log10)
        )

        x_values = true_log10[valid_mask]
        y_values = predicted_log10[valid_mask]

        if len(x_values) == 0:
            raise ValueError(
                f"No finite values were available for {method_name}."
            )

        rmse = float(
            np.sqrt(np.mean((x_values - y_values) ** 2))
        )

        spearman = float(
            pd.Series(x_values).corr(
                pd.Series(y_values),
                method="spearman",
            )
        )

        last_hexbin = ax.hexbin(
            x_values,
            y_values,
            gridsize=50,
            mincnt=1,
            cmap="viridis",
            linewidths=0.0,
        )

        axis_min = float(
            min(x_values.min(), y_values.min())
        )
        axis_max = float(
            max(x_values.max(), y_values.max())
        )

        ax.plot(
            [axis_min, axis_max],
            [axis_min, axis_max],
            linestyle="--",
            color="red",
            linewidth=1.5,
        )

        ax.set_xlim(axis_min, axis_max)
        ax.set_ylim(axis_min, axis_max)

        annotation = (
            f"n = {len(x_values):,}\n"
            f"RMSE = {rmse:.3f}\n"
            f"Spearman = {spearman:.3f}"
        )

        ax.text(
            0.04,
            0.96,
            annotation,
            transform=ax.transAxes,
            ha="left",
            va="top",
            fontsize=9.2,
            fontweight="bold",
            bbox={
                "boxstyle": "round,pad=0.30",
                "facecolor": "white",
                "edgecolor": "black",
                "alpha": 0.90,
            },
        )

        beautify_axis(
            ax,
            xlabel="log10(Reference RA + 1e-8)",
            ylabel=(
                f"log10({METHOD_SHORT[method_name]} prediction + 1e-8)"
            ),
            title=method_name,
        )

    if last_hexbin is not None:
        colorbar = fig.colorbar(
            last_hexbin,
            ax=axes.ravel().tolist(),
            shrink=0.90,
            pad=0.02,
        )
        colorbar.set_label(
            "Number of OTU records",
            fontsize=10.5,
            fontweight="bold",
        )
        colorbar.ax.tick_params(labelsize=9)

    fig.suptitle(
        "Figure 3. Reference abundance vs predicted abundance",
        fontsize=15,
        fontweight="bold",
        y=0.995,
    )

    fig.subplots_adjust(
        left=0.07,
        right=0.92,
        bottom=0.14,
        top=0.88,
        wspace=0.28,
    )

    save_figure(
        fig,
        "Figure3_true_vs_pred_hexbin_combined",
    )
    plt.close(fig)


# ============================================================
# 9. Figure 4: Representative RAD reconstruction
# ============================================================

def plot_rad_examples(
    test_predictions: pd.DataFrame,
) -> None:
    """Plot RAD reconstruction for best, median and worst RF samples."""

    print_step(
        5,
        "Create Figure 4: representative RAD reconstructions",
    )

    representative_samples = choose_representative_samples(
        test_predictions
    )

    sample_roles = [
        "Best RF sample",
        "Median RF sample",
        "Worst RF sample",
    ]

    panel_count = len(representative_samples)

    fig, axes_object = plt.subplots(
        1,
        panel_count,
        figsize=(5.4 * panel_count, 5.2),
        squeeze=False,
    )

    axes = axes_object.ravel()

    for ax, sample_id, sample_role in zip(
        axes,
        representative_samples,
        sample_roles,
    ):
        current = get_one_repeat_sample(
            prediction_df=test_predictions,
            sample_id=sample_id,
            repeat_id=RAD_REPEAT_ID,
        )

        true_ra = safe_compositional_normalisation(
            current["target_reference_ra"].to_numpy(dtype=float)
        )
        raw_ra = safe_compositional_normalisation(
            current["pred_raw_shallow_ra"].to_numpy(dtype=float)
        )
        rf_ra = safe_compositional_normalisation(
            current["pred_random_forest_ra"].to_numpy(dtype=float)
        )
        xgb_ra = safe_compositional_normalisation(
            current["pred_xgboost_ra"].to_numpy(dtype=float)
        )

        rank = np.arange(1, len(true_ra) + 1)

        rad_series = [
            (
                "Reference",
                np.sort(true_ra)[::-1],
                "black",
                "-",
                2.0,
            ),
            (
                "Raw",
                np.sort(raw_ra)[::-1],
                METHOD_COLORS["Raw shallow RA"],
                "--",
                1.7,
            ),
            (
                "RF",
                np.sort(rf_ra)[::-1],
                METHOD_COLORS["Random Forest"],
                "-",
                1.8,
            ),
            (
                "XGB",
                np.sort(xgb_ra)[::-1],
                METHOD_COLORS["XGBoost"],
                "-.",
                1.7,
            ),
        ]

        for label, values, color, linestyle, linewidth in rad_series:
            ax.plot(
                rank,
                np.log10(values + PSEUDO_COUNT),
                color=color,
                linestyle=linestyle,
                linewidth=linewidth,
                label=label,
            )

        ax.set_xscale("log")

        beautify_axis(
            ax,
            xlabel="Rank (log scale)",
            ylabel="log10(Relative abundance + 1e-8)",
            title=f"{sample_role}\nsample_id = {sample_id}",
        )

    axes[0].legend(
        frameon=False,
        fontsize=9,
        loc="upper right",
    )

    fig.suptitle(
        "Figure 4. Representative rank-abundance reconstructions",
        fontsize=15,
        fontweight="bold",
        y=0.995,
    )

    fig.tight_layout(rect=(0, 0, 1, 0.94))

    save_figure(
        fig,
        "Figure4_RAD_examples_combined",
    )
    plt.close(fig)


# ============================================================
# 10. Figure 5: Zero and abundance-group recovery
# ============================================================

def prepare_abundance_improvement_table(
    abundance_improvements: pd.DataFrame,
) -> tuple[pd.DataFrame, str, str, str, str]:
    """Resolve accepted Stage-12 column names for abundance improvements."""

    group_column = first_existing_column(
        abundance_improvements,
        ["abundance_group", "reference_abundance_group"],
        "12_abundance_group_improvement_vs_raw.csv",
    )

    method_column = first_existing_column(
        abundance_improvements,
        ["model", "method"],
        "12_abundance_group_improvement_vs_raw.csv",
    )

    metric_column = first_existing_column(
        abundance_improvements,
        ["metric"],
        "12_abundance_group_improvement_vs_raw.csv",
    )

    value_column = first_existing_column(
        abundance_improvements,
        [
            "relative_improvement_percent",
            "improvement_percent",
            "relative_improvement_percent_vs_raw",
        ],
        "12_abundance_group_improvement_vs_raw.csv",
    )

    output = normalise_method_names(
        abundance_improvements,
        method_column,
    )

    output = normalise_abundance_groups(
        output,
        group_column,
    )

    return (
        output,
        group_column,
        method_column,
        metric_column,
        value_column,
    )


def prepare_zero_improvement_table(
    zero_improvements: pd.DataFrame,
) -> tuple[pd.DataFrame, str, str, str]:
    """Resolve accepted Stage-12 column names for zero improvements."""

    method_column = first_existing_column(
        zero_improvements,
        ["model", "method"],
        "12_zero_recovery_improvement_vs_raw.csv",
    )

    metric_column = first_existing_column(
        zero_improvements,
        ["metric"],
        "12_zero_recovery_improvement_vs_raw.csv",
    )

    value_column = first_existing_column(
        zero_improvements,
        [
            "relative_improvement_percent",
            "improvement_percent",
            "relative_improvement_percent_vs_raw",
        ],
        "12_zero_recovery_improvement_vs_raw.csv",
    )

    output = normalise_method_names(
        zero_improvements,
        method_column,
    )

    return (
        output,
        method_column,
        metric_column,
        value_column,
    )


def plot_recovery_improvements(
    abundance_improvements: pd.DataFrame,
    zero_improvements: pd.DataFrame,
) -> None:
    """Plot zero-recovery and abundance-stratified improvements."""

    print_step(
        6,
        "Create Figure 5: zero and abundance-group recovery",
    )

    (
        abundance_data,
        abundance_group_column,
        abundance_method_column,
        abundance_metric_column,
        abundance_value_column,
    ) = prepare_abundance_improvement_table(
        abundance_improvements
    )

    (
        zero_data,
        zero_method_column,
        zero_metric_column,
        zero_value_column,
    ) = prepare_zero_improvement_table(
        zero_improvements
    )

    fig, axes = plt.subplots(
        1,
        3,
        figsize=(17.0, 5.4),
    )

    bar_width = 0.34

    # Panel A: shallow-zero recovery
    ax = axes[0]
    x_positions = np.arange(len(ZERO_METRIC_ORDER))

    rf_values = []
    xgb_values = []

    for metric in ZERO_METRIC_ORDER:
        rf_values.append(
            extract_improvement_values(
                data=zero_data,
                group_column=zero_metric_column,
                group_value=metric,
                metric_column=zero_metric_column,
                metric_value=metric,
                method_column=zero_method_column,
                method_value="Random Forest",
                value_column=zero_value_column,
            )
        )

        xgb_values.append(
            extract_improvement_values(
                data=zero_data,
                group_column=zero_metric_column,
                group_value=metric,
                metric_column=zero_metric_column,
                metric_value=metric,
                method_column=zero_method_column,
                method_value="XGBoost",
                value_column=zero_value_column,
            )
        )

    ax.bar(
        x_positions - bar_width / 2,
        rf_values,
        width=bar_width,
        color=METHOD_COLORS["Random Forest"],
        edgecolor="black",
        linewidth=0.9,
        label="RF",
    )

    ax.bar(
        x_positions + bar_width / 2,
        xgb_values,
        width=bar_width,
        color=METHOD_COLORS["XGBoost"],
        edgecolor="black",
        linewidth=0.9,
        label="XGB",
    )

    ax.axhline(
        0,
        color="black",
        linestyle="--",
        linewidth=1.0,
    )

    ax.set_xticks(x_positions)
    ax.set_xticklabels(
        [ZERO_METRIC_LABELS[metric] for metric in ZERO_METRIC_ORDER]
    )

    beautify_axis(
        ax,
        xlabel="Metric",
        ylabel="Improvement over Raw (%)",
        title="Zero-recovery improvement",
    )

    ax.legend(
        frameon=False,
        fontsize=9,
    )

    # Panels B-C: abundance-group improvements
    abundance_metric_candidates = [
        (
            ["RMSE_RA", "composition_RMSE_RA"],
            "Abundance-stratified improvement\nRMSE (RA scale)",
        ),
        (
            ["RMSE_log10_RA", "RMSE_log10"],
            "Abundance-stratified improvement\nRMSE (log10 scale)",
        ),
    ]

    available_abundance_metrics = set(
        abundance_data[abundance_metric_column]
        .dropna()
        .astype(str)
        .tolist()
    )

    for ax, (metric_candidates, panel_title) in zip(
        axes[1:],
        abundance_metric_candidates,
    ):
        selected_metric = next(
            (
                metric
                for metric in metric_candidates
                if metric in available_abundance_metrics
            ),
            None,
        )

        if selected_metric is None:
            raise ValueError(
                "The abundance-improvement table does not contain an "
                f"accepted metric from: {metric_candidates}\n"
                f"Available metrics: {sorted(available_abundance_metrics)}"
            )

        x_positions = np.arange(len(ABUNDANCE_ORDER))

        rf_values = []
        xgb_values = []

        for abundance_group in ABUNDANCE_ORDER:
            rf_values.append(
                extract_improvement_values(
                    data=abundance_data,
                    group_column=abundance_group_column,
                    group_value=abundance_group,
                    metric_column=abundance_metric_column,
                    metric_value=selected_metric,
                    method_column=abundance_method_column,
                    method_value="Random Forest",
                    value_column=abundance_value_column,
                )
            )

            xgb_values.append(
                extract_improvement_values(
                    data=abundance_data,
                    group_column=abundance_group_column,
                    group_value=abundance_group,
                    metric_column=abundance_metric_column,
                    metric_value=selected_metric,
                    method_column=abundance_method_column,
                    method_value="XGBoost",
                    value_column=abundance_value_column,
                )
            )

        ax.bar(
            x_positions - bar_width / 2,
            rf_values,
            width=bar_width,
            color=METHOD_COLORS["Random Forest"],
            edgecolor="black",
            linewidth=0.9,
            label="RF",
        )

        ax.bar(
            x_positions + bar_width / 2,
            xgb_values,
            width=bar_width,
            color=METHOD_COLORS["XGBoost"],
            edgecolor="black",
            linewidth=0.9,
            label="XGB",
        )

        ax.axhline(
            0,
            color="black",
            linestyle="--",
            linewidth=1.0,
        )

        ax.set_xticks(x_positions)
        ax.set_xticklabels(
            [
                ABUNDANCE_SHORT[group]
                for group in ABUNDANCE_ORDER
            ],
            rotation=18,
            ha="right",
        )

        beautify_axis(
            ax,
            xlabel="Reference abundance group",
            ylabel="Improvement over Raw (%)",
            title=panel_title,
        )

    fig.suptitle(
        "Figure 5. Zero-recovery and abundance-stratified improvements",
        fontsize=15,
        fontweight="bold",
        y=0.995,
    )

    fig.tight_layout(rect=(0, 0, 1, 0.94))

    save_figure(
        fig,
        "Figure5_zero_recovery_and_abundance_combined",
    )
    plt.close(fig)


# ============================================================
# 11. Main workflow
# ============================================================

def main() -> None:
    """Run the complete core-figure workflow."""

    (
        sample_level_metrics,
        paired_improvements,
        abundance_improvements,
        zero_improvements,
        test_predictions,
    ) = read_inputs()

    plot_primary_metrics(
        sample_level_metrics
    )

    plot_sample_improvements(
        paired_improvements
    )

    plot_reference_vs_prediction(
        test_predictions
    )

    plot_rad_examples(
        test_predictions
    )

    plot_recovery_improvements(
        abundance_improvements,
        zero_improvements,
    )

    print_step(7, "Core figure generation completed successfully")

    print("\nCreated figure sets:")
    print("  1. Figure1_primary_metrics_combined")
    print("  2. Figure2_sample_level_improvement_combined")
    print("  3. Figure3_true_vs_pred_hexbin_combined")
    print("  4. Figure4_RAD_examples_combined")
    print("  5. Figure5_zero_recovery_and_abundance_combined")
    print("\nEach figure was saved as PNG, PDF and SVG.")
    print(f"\nOutput directory:\n{OUTPUT_DIR}")


if __name__ == "__main__":
    main()
