# -*- coding: utf-8 -*-
"""
Author: Ximan Ding
Script: 17_plot_shap_figures.py
Description:
    Create the final SHAP interpretation figures for the Random Forest and
    XGBoost abundance-recovery models.

    This script:
    1. Reads SHAP values and summary tables generated by
       14_compute_shap_results.py;
    2. Checks the required columns and input files;
    3. Plots global mean absolute SHAP importance and beeswarm distributions;
    4. Plots subgroup SHAP importance heatmaps by reference-abundance group
       and shallow-detection status;
    5. Plots Random Forest SHAP dependence relationships for its four leading
       predictors;
    6. Plots representative local SHAP contribution cases;
    7. Saves every figure as PNG, PDF, and SVG.

Inputs:
    results/shap/02_random_forest_shap_values.pkl.gz
    results/shap/03_xgboost_shap_values.pkl.gz
    results/shap/04_global_shap_importance.csv
    results/shap/05_subgroup_shap_importance.csv
    results/shap/07_local_shap_cases.csv
    results/shap/08_shap_additivity_check.csv  (optional)

Outputs:
    results/figures/shap/17_global_shap_combined.png
    results/figures/shap/17_global_shap_combined.pdf
    results/figures/shap/17_global_shap_combined.svg
    results/figures/shap/17_subgroup_shap_heatmaps.png
    results/figures/shap/17_subgroup_shap_heatmaps.pdf
    results/figures/shap/17_subgroup_shap_heatmaps.svg
    results/figures/shap/17_rf_shap_dependence.png
    results/figures/shap/17_rf_shap_dependence.pdf
    results/figures/shap/17_rf_shap_dependence.svg
    results/figures/shap/17_local_shap_cases.png
    results/figures/shap/17_local_shap_cases.pdf
    results/figures/shap/17_local_shap_cases.svg

Notes:
    SHAP values explain the models' raw prediction scale:
        log10(reference relative abundance + 1e-8)

    They do not directly represent changes in the final renormalised relative
    abundance and should not be interpreted as ecological causal effects.
"""

from __future__ import annotations

from pathlib import Path
import warnings

import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib.cm import ScalarMappable
from matplotlib.colors import Normalize
import numpy as np
import pandas as pd
import seaborn as sns
from scipy.stats import spearmanr

warnings.filterwarnings("ignore")

try:
    from statsmodels.nonparametric.smoothers_lowess import lowess

    HAS_LOWESS = True
except Exception:
    HAS_LOWESS = False


# ============================================================================
# 1. Project paths
# ============================================================================

try:
    from _paths import PROJECT_ROOT, RESULTS_DIR  # type: ignore
except (ImportError, AttributeError):
    PROJECT_ROOT = Path(__file__).resolve().parents[1]
    RESULTS_DIR = PROJECT_ROOT / "results"

SHAP_DIR = RESULTS_DIR / "shap"
OUTPUT_DIR = RESULTS_DIR / "figures" / "shap"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

RF_SHAP_FILE = SHAP_DIR / "02_random_forest_shap_values.pkl.gz"
XGB_SHAP_FILE = SHAP_DIR / "03_xgboost_shap_values.pkl.gz"
GLOBAL_IMPORTANCE_FILE = SHAP_DIR / "04_global_shap_importance.csv"
SUBGROUP_IMPORTANCE_FILE = SHAP_DIR / "05_subgroup_shap_importance.csv"
LOCAL_CASES_FILE = SHAP_DIR / "07_local_shap_cases.csv"
ADDITIVITY_FILE = SHAP_DIR / "08_shap_additivity_check.csv"


# ============================================================================
# 2. Plotting configuration
# ============================================================================

mpl.rcParams["font.family"] = "serif"
mpl.rcParams["font.serif"] = ["Times New Roman", "DejaVu Serif"]
mpl.rcParams["font.weight"] = "bold"
mpl.rcParams["axes.labelweight"] = "bold"
mpl.rcParams["axes.titleweight"] = "bold"
mpl.rcParams["axes.linewidth"] = 1.4
mpl.rcParams["axes.unicode_minus"] = False
mpl.rcParams["xtick.major.width"] = 1.2
mpl.rcParams["ytick.major.width"] = 1.2
mpl.rcParams["xtick.direction"] = "out"
mpl.rcParams["ytick.direction"] = "out"
mpl.rcParams["savefig.bbox"] = "tight"

sns.set_style("white")

MODEL_ORDER = ["Random Forest", "XGBoost"]
MODEL_COLORS = {
    "Random Forest": "#3B82B4",
    "XGBoost": "#D65F5F",
}

FEATURE_COLUMNS = [
    "log1p_shallow_count",
    "log10_shallow_ra",
    "zero_in_shallow",
    "shallow_rank_norm",
    "shallow_richness",
    "otu_mean_ra_train",
    "otu_prevalence_train",
    "otu_std_ra_train",
    "otu_max_ra_train",
    "is_other",
]

FEATURE_LABELS = {
    "log1p_shallow_count": "log(1 + shallow count)",
    "log10_shallow_ra": "log10(shallow RA + 1e-8)",
    "zero_in_shallow": "Shallow zero indicator",
    "shallow_rank_norm": "Normalised shallow rank",
    "shallow_richness": "Shallow richness",
    "otu_mean_ra_train": "Training mean RA",
    "otu_prevalence_train": "Training prevalence",
    "otu_std_ra_train": "Training RA SD",
    "otu_max_ra_train": "Training maximum RA",
    "is_other": "OTHER indicator",
}

ABUNDANCE_ORDER = [
    "Dominant (>=1e-2)",
    "Common (1e-3 to 1e-2)",
    "Rare (1e-4 to 1e-3)",
    "Very rare (<1e-4)",
    "Reference zero",
]

ABUNDANCE_LABELS = {
    "Dominant (>=1e-2)": "Dominant",
    "Common (1e-3 to 1e-2)": "Common",
    "Rare (1e-4 to 1e-3)": "Rare",
    "Very rare (<1e-4)": "Very rare",
    "Reference zero": "Reference zero",
}

DETECTION_ORDER = [
    "Detected in shallow",
    "Shallow zero",
]

N_TOP_FEATURES = 8
RANDOM_STATE = 42
PANEL_LABELS = ["A", "B", "C", "D"]


# ============================================================================
# 3. General helper functions
# ============================================================================

def require_file(file_path: Path) -> None:
    """Raise a clear error when a required input file is missing."""

    if not file_path.exists():
        raise FileNotFoundError(
            "Required SHAP file was not found:\n"
            f"{file_path}\n\n"
            "Please run 14_compute_shap_results.py first."
        )


def require_columns(
    table: pd.DataFrame,
    required_columns: list[str],
    table_name: str,
) -> None:
    """Check that a table contains all columns needed by this script."""

    missing = [column for column in required_columns if column not in table.columns]

    if missing:
        raise ValueError(
            f"{table_name} is missing required columns:\n"
            + "\n".join(f"  - {column}" for column in missing)
        )


def save_figure(fig: plt.Figure, base_name: str) -> None:
    """Save one figure as high-resolution PNG, PDF, and SVG."""

    fig.savefig(
        OUTPUT_DIR / f"{base_name}.png",
        dpi=600,
        facecolor="white",
    )
    fig.savefig(
        OUTPUT_DIR / f"{base_name}.pdf",
        facecolor="white",
    )
    fig.savefig(
        OUTPUT_DIR / f"{base_name}.svg",
        facecolor="white",
    )


def beautify_axis(
    ax: plt.Axes,
    xlabel: str = "",
    ylabel: str = "",
    title: str = "",
    grid_axis: str = "x",
) -> None:
    """Apply a consistent publication-style format to one axis."""

    ax.set_xlabel(xlabel, fontsize=11, fontweight="bold")
    ax.set_ylabel(ylabel, fontsize=11, fontweight="bold")
    ax.set_title(title, fontsize=12, fontweight="bold", pad=9)
    ax.tick_params(axis="both", labelsize=9.5, width=1.1, length=4)

    for tick in ax.get_xticklabels():
        tick.set_fontweight("bold")

    for tick in ax.get_yticklabels():
        tick.set_fontweight("bold")

    for spine in ax.spines.values():
        spine.set_linewidth(1.3)

    if grid_axis in {"x", "y", "both"}:
        ax.grid(
            axis=grid_axis,
            linestyle="--",
            linewidth=0.65,
            alpha=0.28,
        )


def add_panel_label(ax: plt.Axes, label: str) -> None:
    """Add a bold panel label such as A, B, C, or D."""

    ax.text(
        -0.12,
        1.06,
        label,
        transform=ax.transAxes,
        fontsize=14,
        fontweight="bold",
        va="top",
        ha="left",
    )


def get_top_features(
    global_importance: pd.DataFrame,
    model_name: str,
    n_top: int,
) -> list[str]:
    """Return the leading SHAP features for one model."""

    current = (
        global_importance.loc[global_importance["model"] == model_name]
        .sort_values("mean_abs_SHAP", ascending=False)
    )

    features = current["feature"].head(n_top).tolist()

    if not features:
        raise ValueError(f"No SHAP importance rows were found for {model_name}.")

    return features


def percentile_colour_values(values: pd.Series) -> np.ndarray:
    """Convert feature values to percentile ranks between zero and one."""

    numeric = pd.to_numeric(values, errors="coerce")

    if numeric.notna().sum() == 0:
        return np.full(len(values), 0.5)

    numeric = numeric.fillna(numeric.median())

    if numeric.nunique() <= 1:
        return np.full(len(values), 0.5)

    return numeric.rank(method="average", pct=True).to_numpy(dtype=float)


# ============================================================================
# 4. Global SHAP figure functions
# ============================================================================

def plot_importance_bar(
    ax: plt.Axes,
    global_importance: pd.DataFrame,
    model_name: str,
    n_top: int,
) -> None:
    """Plot mean absolute SHAP importance for one model."""

    current = (
        global_importance.loc[global_importance["model"] == model_name]
        .sort_values("mean_abs_SHAP", ascending=False)
        .head(n_top)
        .copy()
        .iloc[::-1]
    )

    labels = [FEATURE_LABELS.get(feature, feature) for feature in current["feature"]]

    ax.barh(
        np.arange(len(current)),
        current["mean_abs_SHAP"],
        color=MODEL_COLORS[model_name],
        edgecolor="black",
        linewidth=0.9,
        alpha=0.90,
    )
    ax.set_yticks(np.arange(len(current)))
    ax.set_yticklabels(labels, fontsize=9.2, fontweight="bold")

    for index, value in enumerate(current["mean_abs_SHAP"]):
        ax.text(
            value,
            index,
            f"  {value:.3f}",
            va="center",
            ha="left",
            fontsize=8.5,
            fontweight="bold",
        )

    beautify_axis(
        ax=ax,
        xlabel="Mean |SHAP value|",
        title=f"{model_name}: global importance",
        grid_axis="x",
    )


def plot_custom_beeswarm(
    ax: plt.Axes,
    shap_table: pd.DataFrame,
    top_features: list[str],
    title: str,
    random_state: int,
) -> None:
    """Plot a compact SHAP beeswarm using percentile-scaled feature colours."""

    rng = np.random.default_rng(random_state)

    for feature_index, feature in enumerate(top_features):
        shap_column = f"SHAP__{feature}"

        if shap_column not in shap_table.columns or feature not in shap_table.columns:
            continue

        shap_values = (
            pd.to_numeric(shap_table[shap_column], errors="coerce")
            .fillna(0.0)
            .to_numpy(dtype=float)
        )
        colour_values = percentile_colour_values(shap_table[feature])
        jitter = rng.normal(loc=0.0, scale=0.105, size=len(shap_values))

        ax.scatter(
            shap_values,
            feature_index + jitter,
            c=colour_values,
            cmap="coolwarm",
            vmin=0,
            vmax=1,
            s=17,
            alpha=0.68,
            edgecolors="none",
            rasterized=True,
        )

    ax.axvline(0, color="black", linestyle="--", linewidth=1.1)
    ax.set_yticks(np.arange(len(top_features)))
    ax.set_yticklabels(
        [FEATURE_LABELS.get(feature, feature) for feature in top_features],
        fontsize=9.2,
        fontweight="bold",
    )
    ax.invert_yaxis()

    beautify_axis(
        ax=ax,
        xlabel="SHAP value",
        title=title,
        grid_axis="x",
    )


def plot_global_shap_figure(
    rf_shap: pd.DataFrame,
    xgb_shap: pd.DataFrame,
    global_importance: pd.DataFrame,
) -> tuple[list[str], list[str]]:
    """Create the combined global SHAP importance and beeswarm figure."""

    print("\n" + "=" * 88)
    print("Step 2: Plot global SHAP importance and distributions")
    print("=" * 88)

    rf_top_features = get_top_features(
        global_importance,
        "Random Forest",
        N_TOP_FEATURES,
    )
    xgb_top_features = get_top_features(
        global_importance,
        "XGBoost",
        N_TOP_FEATURES,
    )

    fig, axes = plt.subplots(2, 2, figsize=(16.0, 11.0))

    plot_importance_bar(
        axes[0, 0],
        global_importance,
        "Random Forest",
        N_TOP_FEATURES,
    )
    plot_custom_beeswarm(
        axes[0, 1],
        rf_shap,
        rf_top_features,
        "Random Forest: SHAP distribution",
        RANDOM_STATE,
    )
    plot_importance_bar(
        axes[1, 0],
        global_importance,
        "XGBoost",
        N_TOP_FEATURES,
    )
    plot_custom_beeswarm(
        axes[1, 1],
        xgb_shap,
        xgb_top_features,
        "XGBoost: SHAP distribution",
        RANDOM_STATE + 1,
    )

    for ax, label in zip(axes.flatten(), PANEL_LABELS):
        add_panel_label(ax, label)

    colour_mapper = ScalarMappable(
        norm=Normalize(vmin=0, vmax=1),
        cmap="coolwarm",
    )
    colour_mapper.set_array([])

    colour_bar = fig.colorbar(
        colour_mapper,
        ax=[axes[0, 1], axes[1, 1]],
        fraction=0.025,
        pad=0.02,
    )
    colour_bar.set_label(
        "Feature value\n(low to high)",
        fontsize=10,
        fontweight="bold",
    )
    colour_bar.set_ticks([0, 1])
    colour_bar.set_ticklabels(["Low", "High"])

    fig.suptitle(
        "Global SHAP interpretation of abundance-recovery models",
        fontsize=16,
        fontweight="bold",
        y=1.01,
    )
    fig.tight_layout(rect=[0, 0, 0.96, 0.98])

    save_figure(fig, "17_global_shap_combined")
    plt.close(fig)

    print("Saved: 17_global_shap_combined.[png|pdf|svg]")

    return rf_top_features, xgb_top_features


# ============================================================================
# 5. Subgroup heatmap functions
# ============================================================================

def build_subgroup_matrix(
    subgroup_importance: pd.DataFrame,
    model_name: str,
    subgroup_variable: str,
    subgroup_order: list[str],
    top_features: list[str],
) -> pd.DataFrame:
    """Build one subgroup-by-feature SHAP importance matrix."""

    current = subgroup_importance.loc[
        (subgroup_importance["model"] == model_name)
        & (subgroup_importance["subgroup_variable"] == subgroup_variable)
        & (subgroup_importance["feature"].isin(top_features))
    ].copy()

    matrix = current.pivot_table(
        index="subgroup",
        columns="feature",
        values="importance_percent",
        aggfunc="mean",
    )
    matrix = matrix.reindex(index=subgroup_order, columns=top_features)
    matrix.columns = [FEATURE_LABELS.get(feature, feature) for feature in matrix.columns]

    return matrix


def plot_subgroup_heatmaps(
    subgroup_importance: pd.DataFrame,
    rf_top_features: list[str],
    xgb_top_features: list[str],
) -> None:
    """Create abundance-group and shallow-detection SHAP heatmaps."""

    print("\n" + "=" * 88)
    print("Step 3: Plot subgroup SHAP importance heatmaps")
    print("=" * 88)

    combined_top_features: list[str] = []

    for feature in rf_top_features + xgb_top_features:
        if feature not in combined_top_features:
            combined_top_features.append(feature)

    combined_top_features = combined_top_features[:N_TOP_FEATURES]

    heatmap_matrices: dict[tuple[str, str], pd.DataFrame] = {}

    for model_name in MODEL_ORDER:
        heatmap_matrices[(model_name, "abundance_group")] = build_subgroup_matrix(
            subgroup_importance,
            model_name,
            "abundance_group",
            ABUNDANCE_ORDER,
            combined_top_features,
        )
        heatmap_matrices[(model_name, "shallow_detection_group")] = (
            build_subgroup_matrix(
                subgroup_importance,
                model_name,
                "shallow_detection_group",
                DETECTION_ORDER,
                combined_top_features,
            )
        )

    all_values = np.concatenate(
        [matrix.to_numpy(dtype=float).ravel() for matrix in heatmap_matrices.values()]
    )
    all_values = all_values[np.isfinite(all_values)]

    common_vmax = (
        float(np.nanpercentile(all_values, 98)) if len(all_values) > 0 else 50.0
    )
    common_vmax = max(common_vmax, 1.0)

    fig, axes = plt.subplots(2, 2, figsize=(17.0, 10.0))

    heatmap_specs = [
        (
            "Random Forest",
            "abundance_group",
            axes[0, 0],
            "Random Forest: abundance strata",
        ),
        (
            "XGBoost",
            "abundance_group",
            axes[0, 1],
            "XGBoost: abundance strata",
        ),
        (
            "Random Forest",
            "shallow_detection_group",
            axes[1, 0],
            "Random Forest: shallow detection",
        ),
        (
            "XGBoost",
            "shallow_detection_group",
            axes[1, 1],
            "XGBoost: shallow detection",
        ),
    ]

    for panel_index, (model_name, subgroup_variable, ax, title) in enumerate(
        heatmap_specs
    ):
        matrix = heatmap_matrices[(model_name, subgroup_variable)].copy()

        if subgroup_variable == "abundance_group":
            matrix.index = [
                ABUNDANCE_LABELS.get(item, item) for item in matrix.index
            ]

        sns.heatmap(
            matrix,
            cmap="YlOrRd",
            vmin=0,
            vmax=common_vmax,
            annot=True,
            fmt=".1f",
            linewidths=0.7,
            linecolor="white",
            cbar=(panel_index == 3),
            cbar_kws={"label": "Relative SHAP importance (%)"},
            ax=ax,
        )

        ax.set_xlabel("Feature", fontsize=11, fontweight="bold")
        ax.set_ylabel("Subgroup", fontsize=11, fontweight="bold")
        ax.set_title(title, fontsize=12, fontweight="bold", pad=9)
        ax.tick_params(axis="x", labelrotation=25, labelsize=8.8)
        ax.tick_params(axis="y", labelrotation=0, labelsize=9.2)

        for tick in ax.get_xticklabels():
            tick.set_ha("right")
            tick.set_fontweight("bold")

        for tick in ax.get_yticklabels():
            tick.set_fontweight("bold")

        add_panel_label(ax, PANEL_LABELS[panel_index])

    fig.suptitle(
        "SHAP importance across abundance and detection subgroups",
        fontsize=16,
        fontweight="bold",
        y=1.01,
    )
    fig.tight_layout()

    save_figure(fig, "17_subgroup_shap_heatmaps")
    plt.close(fig)

    print("Saved: 17_subgroup_shap_heatmaps.[png|pdf|svg]")


# ============================================================================
# 6. SHAP dependence functions
# ============================================================================

def smooth_dependence_line(
    x: np.ndarray,
    y: np.ndarray,
) -> tuple[np.ndarray, np.ndarray]:
    """Create a LOWESS line, with a binned-median fallback."""

    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)
    valid = np.isfinite(x) & np.isfinite(y)
    x = x[valid]
    y = y[valid]

    if len(x) < 10:
        order = np.argsort(x)
        return x[order], y[order]

    if np.unique(x).size <= 2:
        unique_x = np.sort(np.unique(x))
        median_y = np.asarray([np.median(y[x == value]) for value in unique_x])
        return unique_x, median_y

    if HAS_LOWESS:
        smoothed = lowess(
            endog=y,
            exog=x,
            frac=0.30,
            it=0,
            return_sorted=True,
        )
        return smoothed[:, 0], smoothed[:, 1]

    edges = np.unique(np.quantile(x, np.linspace(0, 1, 21)))

    if len(edges) < 3:
        order = np.argsort(x)
        return x[order], y[order]

    bin_ids = np.digitize(x, edges[1:-1], right=False)
    smooth_x: list[float] = []
    smooth_y: list[float] = []

    for bin_id in np.unique(bin_ids):
        mask = bin_ids == bin_id

        if mask.sum() == 0:
            continue

        smooth_x.append(float(np.median(x[mask])))
        smooth_y.append(float(np.median(y[mask])))

    return np.asarray(smooth_x), np.asarray(smooth_y)


def plot_dependence(
    ax: plt.Axes,
    shap_table: pd.DataFrame,
    feature: str,
    model_name: str,
) -> None:
    """Plot one feature value against its SHAP contribution."""

    shap_column = f"SHAP__{feature}"

    if feature not in shap_table.columns or shap_column not in shap_table.columns:
        raise ValueError(
            f"Dependence plot columns are missing for feature: {feature}"
        )

    x = pd.to_numeric(shap_table[feature], errors="coerce").to_numpy(dtype=float)
    y = pd.to_numeric(shap_table[shap_column], errors="coerce").to_numpy(dtype=float)
    valid = np.isfinite(x) & np.isfinite(y)
    x = x[valid]
    y = y[valid]

    ax.scatter(
        x,
        y,
        s=22,
        alpha=0.48,
        color=MODEL_COLORS[model_name],
        edgecolors="none",
        rasterized=True,
    )

    smooth_x, smooth_y = smooth_dependence_line(x, y)
    order = np.argsort(smooth_x)
    ax.plot(smooth_x[order], smooth_y[order], color="black", linewidth=2.0)
    ax.axhline(0, color="black", linestyle="--", linewidth=1.0, alpha=0.75)

    if len(x) > 2 and np.unique(x).size > 1 and np.unique(y).size > 1:
        rho, _ = spearmanr(x, y)
    else:
        rho = np.nan

    ax.text(
        0.04,
        0.95,
        f"Spearman rho = {rho:.3f}",
        transform=ax.transAxes,
        ha="left",
        va="top",
        fontsize=9.2,
        fontweight="bold",
        bbox={
            "boxstyle": "round,pad=0.25",
            "facecolor": "white",
            "edgecolor": "black",
            "alpha": 0.88,
        },
    )

    label = FEATURE_LABELS.get(feature, feature)
    beautify_axis(
        ax=ax,
        xlabel=label,
        ylabel="SHAP value",
        title=label,
        grid_axis="both",
    )


def plot_rf_dependence_figure(
    rf_shap: pd.DataFrame,
    rf_top_features: list[str],
) -> None:
    """Create dependence plots for the four leading Random Forest features."""

    print("\n" + "=" * 88)
    print("Step 4: Plot Random Forest SHAP dependence relationships")
    print("=" * 88)

    dependence_features = rf_top_features[:4]

    if len(dependence_features) < 4:
        raise ValueError("Fewer than four Random Forest SHAP features were available.")

    fig, axes = plt.subplots(2, 2, figsize=(14.0, 10.0))

    for panel_index, (ax, feature) in enumerate(
        zip(axes.flatten(), dependence_features)
    ):
        plot_dependence(ax, rf_shap, feature, "Random Forest")
        add_panel_label(ax, PANEL_LABELS[panel_index])

    fig.suptitle(
        "Random Forest SHAP dependence for leading predictors",
        fontsize=16,
        fontweight="bold",
        y=1.01,
    )
    fig.tight_layout()

    save_figure(fig, "17_rf_shap_dependence")
    plt.close(fig)

    print("Saved: 17_rf_shap_dependence.[png|pdf|svg]")


# ============================================================================
# 7. Local SHAP case functions
# ============================================================================

def select_case_row(
    local_cases: pd.DataFrame,
    model_name: str,
    preferred_case: str,
) -> pd.Series:
    """Select one preferred local case for a model, with a safe fallback."""

    current = local_cases.loc[local_cases["model"] == model_name].copy()
    preferred = current.loc[current["local_case_type"] == preferred_case]

    if not preferred.empty:
        return preferred.iloc[0]

    if current.empty:
        raise ValueError(f"No local SHAP cases were found for {model_name}.")

    warnings.warn(
        f"Preferred case '{preferred_case}' was not found for {model_name}; "
        "the first available case will be used."
    )
    return current.iloc[0]


def plot_local_contributions(
    ax: plt.Axes,
    row: pd.Series,
    model_name: str,
    case_title: str,
    n_top: int = 7,
) -> None:
    """Plot the leading positive and negative SHAP contributions for one row."""

    contributions: list[dict[str, object]] = []

    for feature in FEATURE_COLUMNS:
        shap_column = f"SHAP__{feature}"

        if shap_column not in row.index or pd.isna(row[shap_column]):
            continue

        contributions.append(
            {
                "feature": feature,
                "label": FEATURE_LABELS.get(feature, feature),
                "shap_value": float(row[shap_column]),
            }
        )

    contribution_df = pd.DataFrame(contributions)

    if contribution_df.empty:
        raise ValueError(
            f"No SHAP contribution columns were available for {model_name}."
        )

    contribution_df["abs_shap"] = contribution_df["shap_value"].abs()
    contribution_df = contribution_df.sort_values("abs_shap", ascending=False)
    top_df = contribution_df.head(n_top).copy()
    remaining = contribution_df.iloc[n_top:]

    if not remaining.empty:
        other_value = float(remaining["shap_value"].sum())
        top_df = pd.concat(
            [
                top_df,
                pd.DataFrame(
                    {
                        "feature": ["other_features"],
                        "label": ["Other features"],
                        "shap_value": [other_value],
                        "abs_shap": [abs(other_value)],
                    }
                ),
            ],
            ignore_index=True,
        )

    top_df = top_df.sort_values("shap_value", ascending=True)
    colours = [
        "#D65F5F" if value > 0 else "#3B82B4"
        for value in top_df["shap_value"]
    ]

    ax.barh(
        np.arange(len(top_df)),
        top_df["shap_value"],
        color=colours,
        edgecolor="black",
        linewidth=0.85,
        alpha=0.90,
    )
    ax.set_yticks(np.arange(len(top_df)))
    ax.set_yticklabels(top_df["label"], fontsize=8.9, fontweight="bold")
    ax.axvline(0, color="black", linewidth=1.1)

    reference_ra = float(row["target_reference_ra"])
    raw_ra = float(row["pred_raw_shallow_ra"])

    if model_name == "Random Forest":
        model_ra = float(row["pred_random_forest_ra"])
    else:
        model_ra = float(row["pred_xgboost_ra"])

    subtitle = (
        f"{case_title}\n"
        f"Reference RA={reference_ra:.3e}, "
        f"Raw={raw_ra:.3e}, "
        f"Model={model_ra:.3e}"
    )

    beautify_axis(
        ax=ax,
        xlabel="SHAP contribution to log10 prediction",
        title=f"{model_name}\n{subtitle}",
        grid_axis="x",
    )


def plot_local_case_figure(local_cases: pd.DataFrame) -> None:
    """Create representative local SHAP contribution plots."""

    print("\n" + "=" * 88)
    print("Step 5: Plot representative local SHAP explanations")
    print("=" * 88)

    local_case_specs = [
        (
            "Random Forest",
            "Largest positive zero recovery",
            "Largest positive zero recovery",
        ),
        (
            "Random Forest",
            "Highest reference RA",
            "Highest reference abundance",
        ),
        (
            "XGBoost",
            "Largest positive zero recovery",
            "Largest positive zero recovery",
        ),
        (
            "XGBoost",
            "Highest reference RA",
            "Highest reference abundance",
        ),
    ]

    fig, axes = plt.subplots(2, 2, figsize=(16.0, 11.0))

    for panel_index, (ax, case_spec) in enumerate(
        zip(axes.flatten(), local_case_specs)
    ):
        model_name, preferred_case, display_title = case_spec
        selected_row = select_case_row(local_cases, model_name, preferred_case)
        plot_local_contributions(
            ax=ax,
            row=selected_row,
            model_name=model_name,
            case_title=display_title,
            n_top=7,
        )
        add_panel_label(ax, PANEL_LABELS[panel_index])

    fig.suptitle(
        "Local SHAP explanations for representative OTU predictions",
        fontsize=16,
        fontweight="bold",
        y=1.01,
    )
    fig.tight_layout()

    save_figure(fig, "17_local_shap_cases")
    plt.close(fig)

    print("Saved: 17_local_shap_cases.[png|pdf|svg]")


# ============================================================================
# 8. Data loading and validation
# ============================================================================

def read_shap_outputs() -> tuple[
    pd.DataFrame,
    pd.DataFrame,
    pd.DataFrame,
    pd.DataFrame,
    pd.DataFrame,
]:
    """Read and validate all SHAP files needed for plotting."""

    print("=" * 88)
    print("Step 1: Read and validate SHAP outputs")
    print("=" * 88)

    for required_file in [
        RF_SHAP_FILE,
        XGB_SHAP_FILE,
        GLOBAL_IMPORTANCE_FILE,
        SUBGROUP_IMPORTANCE_FILE,
        LOCAL_CASES_FILE,
    ]:
        require_file(required_file)

    rf_shap = pd.read_pickle(RF_SHAP_FILE)
    xgb_shap = pd.read_pickle(XGB_SHAP_FILE)
    global_importance = pd.read_csv(GLOBAL_IMPORTANCE_FILE)
    subgroup_importance = pd.read_csv(SUBGROUP_IMPORTANCE_FILE)
    local_cases = pd.read_csv(LOCAL_CASES_FILE)

    require_columns(
        global_importance,
        ["model", "feature", "mean_abs_SHAP"],
        "Global SHAP importance table",
    )
    require_columns(
        subgroup_importance,
        [
            "model",
            "subgroup_variable",
            "subgroup",
            "feature",
            "importance_percent",
        ],
        "Subgroup SHAP importance table",
    )
    require_columns(
        local_cases,
        [
            "model",
            "local_case_type",
            "target_reference_ra",
            "pred_raw_shallow_ra",
            "pred_random_forest_ra",
            "pred_xgboost_ra",
        ],
        "Local SHAP case table",
    )

    if ADDITIVITY_FILE.exists():
        additivity_check = pd.read_csv(ADDITIVITY_FILE)
        print("\nSHAP additivity check:")
        print(additivity_check.to_string(index=False))
    else:
        print("\nOptional additivity-check file was not found; plotting will continue.")

    print(f"\nRandom Forest SHAP table: {rf_shap.shape}")
    print(f"XGBoost SHAP table:      {xgb_shap.shape}")
    print(f"Global importance table: {global_importance.shape}")
    print(f"Subgroup importance:     {subgroup_importance.shape}")
    print(f"Local case table:         {local_cases.shape}")

    return (
        rf_shap,
        xgb_shap,
        global_importance,
        subgroup_importance,
        local_cases,
    )


# ============================================================================
# 9. Main workflow
# ============================================================================

def main() -> None:
    """Run the complete SHAP plotting workflow."""

    (
        rf_shap,
        xgb_shap,
        global_importance,
        subgroup_importance,
        local_cases,
    ) = read_shap_outputs()

    rf_top_features, xgb_top_features = plot_global_shap_figure(
        rf_shap,
        xgb_shap,
        global_importance,
    )

    plot_subgroup_heatmaps(
        subgroup_importance,
        rf_top_features,
        xgb_top_features,
    )

    plot_rf_dependence_figure(
        rf_shap,
        rf_top_features,
    )

    plot_local_case_figure(local_cases)

    print("\n" + "=" * 88)
    print("SHAP figure generation completed")
    print("=" * 88)
    print(f"\nOutput directory:\n{OUTPUT_DIR}\n")
    print(
        "Generated figure groups:\n"
        "  1. 17_global_shap_combined\n"
        "  2. 17_subgroup_shap_heatmaps\n"
        "  3. 17_rf_shap_dependence\n"
        "  4. 17_local_shap_cases\n"
    )
    print("Each figure was saved as PNG, PDF, and SVG.")


if __name__ == "__main__":
    main()
