#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Author: Ximan Ding
# Script: 19_plot_depth_sensitivity.py
# Description:
#     Create publication-ready figures for the sequencing-depth sensitivity
#     analysis generated by 18_run_depth_sensitivity.py.
#
#     This script:
#     1. Reads the combined depth-sensitivity result tables;
#     2. Validates required metrics, depths and methods;
#     3. Plots absolute performance across sequencing depths;
#     4. Plots Random Forest and XGBoost improvement over Raw shallow RA;
#     5. Plots shallow-zero recovery across depths;
#     6. Plots abundance-stratum recovery across depths;
#     7. Plots validation performance and XGBoost model-selection results;
#     8. Exports each figure as PDF, PNG and SVG.
#
# Inputs:
#     results/depth_sensitivity/03_depth_sample_level_metrics.csv
#     results/depth_sensitivity/04_depth_performance_summary.csv
#     results/depth_sensitivity/05_depth_abundance_stratum_metrics.csv
#     results/depth_sensitivity/06_depth_zero_recovery_metrics.csv
#     results/depth_sensitivity/07_depth_model_selection_summary.csv
#     results/depth_sensitivity/08_depth_improvement_vs_raw.csv
#
# Outputs:
#     results/figures/depth_sensitivity/
#         Figure10_depth_performance_curves.pdf/png/svg
#         Figure11_depth_improvement_over_raw.pdf/png/svg
#         Figure12_depth_zero_recovery.pdf/png/svg
#         Figure13_depth_abundance_strata.pdf/png/svg
#         Figure14_depth_model_selection.pdf/png/svg
#
# Notes:
#     - The figure numbers can be renamed later when the final report order is
#       fixed.
#     - No model fitting is performed in this script.
#     - The 2,000-read sensitivity result is an independently resimulated and
#       refitted experiment, so it need not exactly match the main analysis.

from __future__ import annotations

from pathlib import Path
import warnings

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


warnings.filterwarnings("ignore")


# =============================================================================
# 1. Project paths
# =============================================================================

PROJECT_ROOT = Path(__file__).resolve().parents[1]

RESULTS_DIR = PROJECT_ROOT / "results"
DEPTH_RESULTS_DIR = RESULTS_DIR / "depth_sensitivity"
FIGURE_DIR = RESULTS_DIR / "figures" / "depth_sensitivity"

SAMPLE_LEVEL_FILE = (
    DEPTH_RESULTS_DIR / "03_depth_sample_level_metrics.csv"
)
PERFORMANCE_SUMMARY_FILE = (
    DEPTH_RESULTS_DIR / "04_depth_performance_summary.csv"
)
ABUNDANCE_FILE = (
    DEPTH_RESULTS_DIR / "05_depth_abundance_stratum_metrics.csv"
)
ZERO_RECOVERY_FILE = (
    DEPTH_RESULTS_DIR / "06_depth_zero_recovery_metrics.csv"
)
MODEL_SELECTION_FILE = (
    DEPTH_RESULTS_DIR / "07_depth_model_selection_summary.csv"
)
IMPROVEMENT_FILE = (
    DEPTH_RESULTS_DIR / "08_depth_improvement_vs_raw.csv"
)

FIGURE_DIR.mkdir(parents=True, exist_ok=True)


# =============================================================================
# 2. Plot settings
# =============================================================================

EXPECTED_DEPTHS = [500, 1000, 2000, 5000]

METHOD_ORDER = [
    "Raw shallow RA",
    "Training-mean RA",
    "Random Forest",
    "XGBoost",
]

METHOD_LABELS = {
    "Raw shallow RA": "Raw",
    "Training-mean RA": "Training mean",
    "Random Forest": "Random Forest",
    "XGBoost": "XGBoost",
}

MODEL_ORDER = [
    "Random Forest",
    "XGBoost",
]

ABUNDANCE_ORDER = [
    "Dominant (>=1e-2)",
    "Common (1e-3 to 1e-2)",
    "Rare (1e-4 to 1e-3)",
    "Very rare (<1e-4)",
    "Reference zero",
]

ABUNDANCE_LABELS = {
    "Dominant (>=1e-2)": "Dominant",
    "Common (1e-3 to 1e-2)": "Common",
    "Rare (1e-4 to 1e-3)": "Rare",
    "Very rare (<1e-4)": "Very rare",
    "Reference zero": "Reference zero",
}

PRIMARY_METRICS = [
    (
        "Bray_Curtis",
        "Bray-Curtis distance",
        "Bray-Curtis distance",
    ),
    (
        "Jensen_Shannon_distance",
        "Jensen-Shannon distance",
        "Jensen-Shannon distance",
    ),
    (
        "RAD_RMSE_log10_RA_specific",
        "RAD log10-RMSE",
        "RAD log10-RMSE",
    ),
    (
        "RAD_tail_MAE_log10",
        "RAD tail log10-MAE",
        "RAD tail log10-MAE",
    ),
    (
        "Shannon_absolute_error",
        "Shannon absolute error",
        "Shannon absolute error",
    ),
    (
        "richness_1read_absolute_error",
        "One-read richness error",
        "Absolute error in richness",
    ),
]

IMPROVEMENT_METRICS = [
    (
        "Bray_Curtis",
        "Bray-Curtis",
    ),
    (
        "Jensen_Shannon_distance",
        "Jensen-Shannon",
    ),
    (
        "RAD_RMSE_log10_RA_specific",
        "RAD log10-RMSE",
    ),
    (
        "RAD_tail_MAE_log10",
        "RAD tail log10-MAE",
    ),
    (
        "Shannon_absolute_error",
        "Shannon error",
    ),
    (
        "richness_1read_absolute_error",
        "One-read richness error",
    ),
]

DPI = 300
PNG_DPI = 450


# =============================================================================
# 3. General utility functions
# =============================================================================

def print_step(title: str) -> None:
    """Print a clearly separated workflow step."""
    print("\n" + "=" * 100)
    print(title)
    print("=" * 100)


def require_file(path: Path) -> None:
    """Raise a clear error when an expected input file is absent."""
    if not path.exists():
        raise FileNotFoundError(
            "Required file not found:\n"
            f"{path}\n\n"
            "Run code/18_run_depth_sensitivity.py first."
        )


def validate_columns(
    dataframe: pd.DataFrame,
    required_columns: list[str],
    dataframe_name: str,
) -> None:
    """Check that a table contains all required columns."""
    missing = [
        column
        for column in required_columns
        if column not in dataframe.columns
    ]

    if missing:
        raise ValueError(
            f"{dataframe_name} is missing required columns: {missing}"
        )


def save_figure(
    figure: plt.Figure,
    stem: str,
) -> None:
    """Save a figure as PDF, PNG and SVG."""
    pdf_path = FIGURE_DIR / f"{stem}.pdf"
    png_path = FIGURE_DIR / f"{stem}.png"
    svg_path = FIGURE_DIR / f"{stem}.svg"

    figure.savefig(
        pdf_path,
        bbox_inches="tight",
    )
    figure.savefig(
        png_path,
        dpi=PNG_DPI,
        bbox_inches="tight",
    )
    figure.savefig(
        svg_path,
        bbox_inches="tight",
    )

    print(f"Saved: {pdf_path}")
    print(f"Saved: {png_path}")
    print(f"Saved: {svg_path}")


def add_panel_label(
    axis: plt.Axes,
    label: str,
) -> None:
    """Add a bold panel label near the upper-left corner."""
    axis.text(
        -0.12,
        1.08,
        label,
        transform=axis.transAxes,
        fontsize=12,
        fontweight="bold",
        va="top",
        ha="left",
    )


def format_depth_axis(axis: plt.Axes) -> None:
    """Apply consistent sequencing-depth ticks and labels."""
    axis.set_xticks(EXPECTED_DEPTHS)
    axis.set_xticklabels(
        [f"{depth:,}" for depth in EXPECTED_DEPTHS]
    )
    axis.set_xlabel("Shallow sequencing depth (reads)")


def set_common_axis_style(axis: plt.Axes) -> None:
    """Apply restrained publication-style axis formatting."""
    axis.spines["top"].set_visible(False)
    axis.spines["right"].set_visible(False)
    axis.grid(
        axis="y",
        alpha=0.22,
        linewidth=0.7,
    )
    axis.tick_params(
        axis="both",
        labelsize=9,
    )


def select_summary_rows(
    performance_summary: pd.DataFrame,
    metric: str,
) -> pd.DataFrame:
    """Select one metric and enforce the expected plotting order."""
    current = performance_summary.loc[
        performance_summary["metric"] == metric
    ].copy()

    current["method"] = pd.Categorical(
        current["method"],
        categories=METHOD_ORDER,
        ordered=True,
    )

    current = current.sort_values(
        ["method", "depth"]
    )

    return current


def check_expected_depths(
    dataframe: pd.DataFrame,
    dataframe_name: str,
) -> None:
    """Warn if a result table does not contain all intended depths."""
    observed = sorted(
        pd.to_numeric(
            dataframe["depth"],
            errors="coerce",
        )
        .dropna()
        .astype(int)
        .unique()
        .tolist()
    )

    missing = sorted(set(EXPECTED_DEPTHS) - set(observed))

    if missing:
        raise ValueError(
            f"{dataframe_name} is missing depths: {missing}"
        )


# =============================================================================
# 4. Read plotting inputs
# =============================================================================

def read_inputs():
    """Read and validate all tables required by the plotting script."""
    print_step("Step 1: Read and validate depth-sensitivity plotting inputs")

    input_files = [
        SAMPLE_LEVEL_FILE,
        PERFORMANCE_SUMMARY_FILE,
        ABUNDANCE_FILE,
        ZERO_RECOVERY_FILE,
        MODEL_SELECTION_FILE,
        IMPROVEMENT_FILE,
    ]

    for input_file in input_files:
        require_file(input_file)

    sample_level = pd.read_csv(SAMPLE_LEVEL_FILE)
    performance_summary = pd.read_csv(PERFORMANCE_SUMMARY_FILE)
    abundance_metrics = pd.read_csv(ABUNDANCE_FILE)
    zero_metrics = pd.read_csv(ZERO_RECOVERY_FILE)
    model_selection = pd.read_csv(MODEL_SELECTION_FILE)
    improvement = pd.read_csv(IMPROVEMENT_FILE)

    validate_columns(
        sample_level,
        [
            "depth",
            "method",
            "sample_id",
            "Bray_Curtis",
            "Jensen_Shannon_distance",
            "RAD_RMSE_log10_RA_specific",
            "RAD_tail_MAE_log10",
            "Shannon_absolute_error",
            "richness_1read_absolute_error",
        ],
        "Sample-level metrics",
    )

    validate_columns(
        performance_summary,
        [
            "depth",
            "method",
            "metric",
            "n_samples",
            "mean",
            "std",
            "median",
            "q25",
            "q75",
        ],
        "Performance summary",
    )

    validate_columns(
        abundance_metrics,
        [
            "depth",
            "method",
            "abundance_group",
            "number_of_rows",
            "RMSE_RA",
            "RMSE_log10_RA",
        ],
        "Abundance-stratum metrics",
    )

    validate_columns(
        zero_metrics,
        [
            "depth",
            "method",
            "number_of_rows",
            "RMSE_RA",
            "RMSE_log10_RA",
            "positive_prediction_rate",
        ],
        "Zero-recovery metrics",
    )

    validate_columns(
        model_selection,
        [
            "depth",
            "rf_validation_log_rmse",
            "xgb_validation_log_rmse",
            "xgb_best_iteration",
            "rf_first_fit_minutes",
            "xgb_first_fit_minutes",
            "total_depth_minutes",
        ],
        "Model-selection summary",
    )

    validate_columns(
        improvement,
        [
            "depth",
            "metric",
            "model",
            "raw_mean",
            "model_mean",
            "mean_oriented_improvement",
            "improvement_ci_low",
            "improvement_ci_high",
            "relative_improvement_percent",
            "sample_win_rate",
        ],
        "Improvement-over-Raw table",
    )

    for dataframe, name in [
        (sample_level, "Sample-level metrics"),
        (performance_summary, "Performance summary"),
        (abundance_metrics, "Abundance-stratum metrics"),
        (zero_metrics, "Zero-recovery metrics"),
        (model_selection, "Model-selection summary"),
        (improvement, "Improvement-over-Raw table"),
    ]:
        check_expected_depths(dataframe, name)

    print(f"Sample-level metrics:       {sample_level.shape}")
    print(f"Performance summary:        {performance_summary.shape}")
    print(f"Abundance-stratum metrics:  {abundance_metrics.shape}")
    print(f"Zero-recovery metrics:      {zero_metrics.shape}")
    print(f"Model-selection summary:    {model_selection.shape}")
    print(f"Improvement-over-Raw table: {improvement.shape}")
    print(f"Figure directory:           {FIGURE_DIR}")

    return (
        sample_level,
        performance_summary,
        abundance_metrics,
        zero_metrics,
        model_selection,
        improvement,
    )


# =============================================================================
# 5. Figure 10: Absolute performance across depths
# =============================================================================

def plot_depth_performance_curves(
    performance_summary: pd.DataFrame,
) -> None:
    """Plot mean test performance of all four methods across depths."""
    print_step("Step 2: Plot absolute performance across depths")

    figure, axes = plt.subplots(
        2,
        3,
        figsize=(14.5, 8.8),
        constrained_layout=True,
    )

    panel_labels = list("ABCDEF")

    for axis, panel_label, (
        metric,
        title,
        y_label,
    ) in zip(
        axes.flat,
        panel_labels,
        PRIMARY_METRICS,
    ):
        current = select_summary_rows(
            performance_summary,
            metric,
        )

        if current.empty:
            raise ValueError(
                f"No performance-summary rows found for metric: {metric}"
            )

        for method in METHOD_ORDER:
            method_data = current.loc[
                current["method"] == method
            ].sort_values("depth")

            if method_data.empty:
                continue

            x_values = method_data["depth"].to_numpy(dtype=float)
            means = method_data["mean"].to_numpy(dtype=float)
            standard_errors = (
                method_data["std"].to_numpy(dtype=float)
                / np.sqrt(
                    method_data["n_samples"].to_numpy(dtype=float)
                )
            )

            axis.plot(
                x_values,
                means,
                marker="o",
                linewidth=1.8,
                markersize=5,
                label=METHOD_LABELS[method],
            )

            axis.fill_between(
                x_values,
                means - standard_errors,
                means + standard_errors,
                alpha=0.12,
            )

        axis.set_title(
            title,
            fontsize=11,
            fontweight="bold",
        )
        axis.set_ylabel(y_label)
        format_depth_axis(axis)
        set_common_axis_style(axis)
        add_panel_label(axis, panel_label)

    handles, labels = axes[0, 0].get_legend_handles_labels()

    figure.legend(
        handles,
        labels,
        loc="upper center",
        ncol=4,
        frameon=False,
        bbox_to_anchor=(0.5, 1.035),
    )

    figure.suptitle(
        "Figure 10. Test performance across shallow sequencing depths",
        fontsize=15,
        fontweight="bold",
        y=1.075,
    )

    save_figure(
        figure,
        "Figure10_depth_performance_curves",
    )
    plt.close(figure)


# =============================================================================
# 6. Figure 11: Relative improvement over Raw
# =============================================================================

def plot_improvement_over_raw(
    improvement: pd.DataFrame,
) -> None:
    """Plot percentage improvement of RF and XGBoost over Raw shallow RA."""
    print_step("Step 3: Plot model improvement over Raw shallow RA")

    figure, axes = plt.subplots(
        2,
        3,
        figsize=(14.5, 8.8),
        constrained_layout=True,
    )

    panel_labels = list("ABCDEF")

    for axis, panel_label, (
        metric,
        title,
    ) in zip(
        axes.flat,
        panel_labels,
        IMPROVEMENT_METRICS,
    ):
        current = improvement.loc[
            improvement["metric"] == metric
        ].copy()

        if current.empty:
            raise ValueError(
                f"No improvement rows found for metric: {metric}"
            )

        for model in MODEL_ORDER:
            model_data = current.loc[
                current["model"] == model
            ].sort_values("depth")

            if model_data.empty:
                continue

            axis.plot(
                model_data["depth"],
                model_data["relative_improvement_percent"],
                marker="o",
                linewidth=1.8,
                markersize=5,
                label=METHOD_LABELS[model],
            )

        axis.axhline(
            0.0,
            linestyle="--",
            linewidth=1.0,
        )

        axis.set_title(
            title,
            fontsize=11,
            fontweight="bold",
        )
        axis.set_ylabel("Improvement over Raw (%)")
        format_depth_axis(axis)
        set_common_axis_style(axis)
        add_panel_label(axis, panel_label)

    handles, labels = axes[0, 0].get_legend_handles_labels()

    figure.legend(
        handles,
        labels,
        loc="upper center",
        ncol=2,
        frameon=False,
        bbox_to_anchor=(0.5, 1.035),
    )

    figure.suptitle(
        "Figure 11. Model improvement over Raw shallow RA across depths",
        fontsize=15,
        fontweight="bold",
        y=1.075,
    )

    save_figure(
        figure,
        "Figure11_depth_improvement_over_raw",
    )
    plt.close(figure)


# =============================================================================
# 7. Figure 12: Shallow-zero recovery
# =============================================================================

def plot_zero_recovery(
    zero_metrics: pd.DataFrame,
) -> None:
    """Plot zero-record counts and shallow-zero recovery performance."""
    print_step("Step 4: Plot shallow-zero recovery across depths")

    figure, axes = plt.subplots(
        2,
        2,
        figsize=(11.8, 8.4),
        constrained_layout=True,
    )

    # Panel A: number of shallow-zero, reference-positive records
    record_counts = (
        zero_metrics.loc[
            zero_metrics["method"] == "Raw shallow RA",
            ["depth", "number_of_rows"],
        ]
        .drop_duplicates(subset=["depth"])
        .sort_values("depth")
    )

    axes[0, 0].plot(
        record_counts["depth"],
        record_counts["number_of_rows"],
        marker="o",
        linewidth=1.8,
    )
    axes[0, 0].set_title(
        "Shallow-zero, reference-positive records",
        fontsize=11,
        fontweight="bold",
    )
    axes[0, 0].set_ylabel("Number of OTU records")
    format_depth_axis(axes[0, 0])
    set_common_axis_style(axes[0, 0])
    add_panel_label(axes[0, 0], "A")

    # Panel B: RA-scale RMSE
    for method in METHOD_ORDER:
        current = zero_metrics.loc[
            zero_metrics["method"] == method
        ].sort_values("depth")

        if current.empty:
            continue

        axes[0, 1].plot(
            current["depth"],
            current["RMSE_RA"],
            marker="o",
            linewidth=1.8,
            label=METHOD_LABELS[method],
        )

    axes[0, 1].set_title(
        "Zero-recovery RMSE on the RA scale",
        fontsize=11,
        fontweight="bold",
    )
    axes[0, 1].set_ylabel("RMSE (RA)")
    format_depth_axis(axes[0, 1])
    set_common_axis_style(axes[0, 1])
    add_panel_label(axes[0, 1], "B")

    # Panel C: log10-scale RMSE
    for method in METHOD_ORDER:
        current = zero_metrics.loc[
            zero_metrics["method"] == method
        ].sort_values("depth")

        if current.empty:
            continue

        axes[1, 0].plot(
            current["depth"],
            current["RMSE_log10_RA"],
            marker="o",
            linewidth=1.8,
            label=METHOD_LABELS[method],
        )

    axes[1, 0].set_title(
        "Zero-recovery RMSE on the log10 scale",
        fontsize=11,
        fontweight="bold",
    )
    axes[1, 0].set_ylabel("RMSE (log10 RA)")
    format_depth_axis(axes[1, 0])
    set_common_axis_style(axes[1, 0])
    add_panel_label(axes[1, 0], "C")

    # Panel D: positive prediction rate
    for method in METHOD_ORDER:
        current = zero_metrics.loc[
            zero_metrics["method"] == method
        ].sort_values("depth")

        if current.empty:
            continue

        axes[1, 1].plot(
            current["depth"],
            current["positive_prediction_rate"] * 100,
            marker="o",
            linewidth=1.8,
            label=METHOD_LABELS[method],
        )

    axes[1, 1].set_title(
        "Positive prediction rate for shallow zeros",
        fontsize=11,
        fontweight="bold",
    )
    axes[1, 1].set_ylabel("Positive prediction rate (%)")
    axes[1, 1].set_ylim(-3, 103)
    format_depth_axis(axes[1, 1])
    set_common_axis_style(axes[1, 1])
    add_panel_label(axes[1, 1], "D")

    handles, labels = axes[0, 1].get_legend_handles_labels()

    figure.legend(
        handles,
        labels,
        loc="upper center",
        ncol=4,
        frameon=False,
        bbox_to_anchor=(0.5, 1.035),
    )

    figure.suptitle(
        "Figure 12. Shallow-zero recovery across sequencing depths",
        fontsize=15,
        fontweight="bold",
        y=1.075,
    )

    save_figure(
        figure,
        "Figure12_depth_zero_recovery",
    )
    plt.close(figure)


# =============================================================================
# 8. Figure 13: Abundance-stratum recovery
# =============================================================================

def calculate_abundance_improvement(
    abundance_metrics: pd.DataFrame,
    metric: str,
) -> pd.DataFrame:
    """
    Calculate error improvement over Raw within each depth and abundance group.

    Positive percentages indicate that the ML model has lower error than Raw.
    Improvement is undefined when Raw error is zero.
    """
    current = abundance_metrics[
        [
            "depth",
            "method",
            "abundance_group",
            metric,
        ]
    ].copy()

    wide = current.pivot_table(
        index=["depth", "abundance_group"],
        columns="method",
        values=metric,
        aggfunc="first",
    ).reset_index()

    records = []

    for _, row in wide.iterrows():
        if "Raw shallow RA" not in wide.columns:
            continue

        raw_value = row.get("Raw shallow RA", np.nan)

        for model in MODEL_ORDER:
            model_value = row.get(model, np.nan)

            if (
                pd.isna(raw_value)
                or pd.isna(model_value)
                or abs(raw_value) <= 1e-15
            ):
                improvement = np.nan
            else:
                improvement = (
                    (raw_value - model_value)
                    / abs(raw_value)
                    * 100
                )

            records.append(
                {
                    "depth": int(row["depth"]),
                    "abundance_group": row["abundance_group"],
                    "model": model,
                    "metric": metric,
                    "improvement_percent": improvement,
                }
            )

    return pd.DataFrame(records)


def plot_abundance_strata(
    abundance_metrics: pd.DataFrame,
) -> None:
    """Plot abundance-stratum error improvement across sequencing depths."""
    print_step("Step 5: Plot abundance-stratum recovery across depths")

    ra_improvement = calculate_abundance_improvement(
        abundance_metrics,
        "RMSE_RA",
    )

    log_improvement = calculate_abundance_improvement(
        abundance_metrics,
        "RMSE_log10_RA",
    )

    figure, axes = plt.subplots(
        2,
        2,
        figsize=(13.0, 9.2),
        constrained_layout=True,
    )

    plot_specs = [
        (
            axes[0, 0],
            ra_improvement,
            "Random Forest",
            "RF improvement: RA-scale RMSE",
            "A",
        ),
        (
            axes[0, 1],
            ra_improvement,
            "XGBoost",
            "XGBoost improvement: RA-scale RMSE",
            "B",
        ),
        (
            axes[1, 0],
            log_improvement,
            "Random Forest",
            "RF improvement: log10-scale RMSE",
            "C",
        ),
        (
            axes[1, 1],
            log_improvement,
            "XGBoost",
            "XGBoost improvement: log10-scale RMSE",
            "D",
        ),
    ]

    for axis, dataframe, model, title, panel_label in plot_specs:
        model_data = dataframe.loc[
            dataframe["model"] == model
        ].copy()

        for abundance_group in ABUNDANCE_ORDER:
            group_data = model_data.loc[
                model_data["abundance_group"] == abundance_group
            ].sort_values("depth")

            if group_data.empty:
                continue

            if group_data["improvement_percent"].notna().sum() == 0:
                continue

            axis.plot(
                group_data["depth"],
                group_data["improvement_percent"],
                marker="o",
                linewidth=1.6,
                markersize=4.5,
                label=ABUNDANCE_LABELS[abundance_group],
            )

        axis.axhline(
            0.0,
            linestyle="--",
            linewidth=1.0,
        )
        axis.set_title(
            title,
            fontsize=11,
            fontweight="bold",
        )
        axis.set_ylabel("Improvement over Raw (%)")
        format_depth_axis(axis)
        set_common_axis_style(axis)
        add_panel_label(axis, panel_label)

    handles, labels = axes[0, 0].get_legend_handles_labels()

    figure.legend(
        handles,
        labels,
        loc="upper center",
        ncol=5,
        frameon=False,
        bbox_to_anchor=(0.5, 1.035),
    )

    figure.suptitle(
        "Figure 13. Abundance-stratum recovery across sequencing depths",
        fontsize=15,
        fontweight="bold",
        y=1.075,
    )

    save_figure(
        figure,
        "Figure13_depth_abundance_strata",
    )
    plt.close(figure)


# =============================================================================
# 9. Figure 14: Validation and model selection
# =============================================================================

def plot_model_selection(
    model_selection: pd.DataFrame,
) -> None:
    """Plot validation RMSE, selected tree count and runtime by depth."""
    print_step("Step 6: Plot validation performance and model selection")

    current = model_selection.sort_values("depth").copy()

    figure, axes = plt.subplots(
        1,
        3,
        figsize=(14.2, 4.5),
        constrained_layout=True,
    )

    # Panel A: validation RMSE
    axes[0].plot(
        current["depth"],
        current["rf_validation_log_rmse"],
        marker="o",
        linewidth=1.8,
        label="Random Forest",
    )

    axes[0].plot(
        current["depth"],
        current["xgb_validation_log_rmse"],
        marker="o",
        linewidth=1.8,
        label="XGBoost",
    )

    axes[0].set_title(
        "Validation log10-RMSE",
        fontsize=11,
        fontweight="bold",
    )
    axes[0].set_ylabel("Validation log10-RMSE")
    format_depth_axis(axes[0])
    set_common_axis_style(axes[0])
    add_panel_label(axes[0], "A")
    axes[0].legend(frameon=False)

    # Panel B: selected XGBoost tree count
    axes[1].plot(
        current["depth"],
        current["xgb_best_iteration"],
        marker="o",
        linewidth=1.8,
    )

    axes[1].set_title(
        "Selected XGBoost tree count",
        fontsize=11,
        fontweight="bold",
    )
    axes[1].set_ylabel("Best iteration")
    format_depth_axis(axes[1])
    set_common_axis_style(axes[1])
    add_panel_label(axes[1], "B")

    # Panel C: runtime
    axes[2].plot(
        current["depth"],
        current["rf_first_fit_minutes"],
        marker="o",
        linewidth=1.8,
        label="RF first fit",
    )

    axes[2].plot(
        current["depth"],
        current["xgb_first_fit_minutes"],
        marker="o",
        linewidth=1.8,
        label="XGB first fit",
    )

    axes[2].plot(
        current["depth"],
        current["total_depth_minutes"],
        marker="o",
        linewidth=1.8,
        label="Total depth run",
    )

    axes[2].set_title(
        "Model-fitting and total runtime",
        fontsize=11,
        fontweight="bold",
    )
    axes[2].set_ylabel("Runtime (minutes)")
    format_depth_axis(axes[2])
    set_common_axis_style(axes[2])
    add_panel_label(axes[2], "C")
    axes[2].legend(frameon=False)

    figure.suptitle(
        "Figure 14. Validation performance and depth-specific model selection",
        fontsize=15,
        fontweight="bold",
        y=1.06,
    )

    save_figure(
        figure,
        "Figure14_depth_model_selection",
    )
    plt.close(figure)


# =============================================================================
# 10. Main workflow
# =============================================================================

def main() -> None:
    """Run the complete depth-sensitivity plotting workflow."""
    (
        _sample_level,
        performance_summary,
        abundance_metrics,
        zero_metrics,
        model_selection,
        improvement,
    ) = read_inputs()

    plot_depth_performance_curves(
        performance_summary
    )

    plot_improvement_over_raw(
        improvement
    )

    plot_zero_recovery(
        zero_metrics
    )

    plot_abundance_strata(
        abundance_metrics
    )

    plot_model_selection(
        model_selection
    )

    print_step("Depth-sensitivity figures completed")
    print(f"Figure directory: {FIGURE_DIR}")
    print("Generated figure groups:")
    print("  - Figure10_depth_performance_curves")
    print("  - Figure11_depth_improvement_over_raw")
    print("  - Figure12_depth_zero_recovery")
    print("  - Figure13_depth_abundance_strata")
    print("  - Figure14_depth_model_selection")


if __name__ == "__main__":
    main()
